const musicContainer = document.getElementById("music-container")
const playBtn = document.getElementById("play")
const prevBtn = document.getElementById("prev")
const nextBtn = document.getElementById("next")

const audio = document.getElementById("audio")
const progress = document.getElementById("progress")
const progressContainer = document.getElementById("progress-container")
const title = document.getElementById("title")
const musicCover = document.getElementById("music-cover")
const jdt = document.querySelector('#progress-container')

// 获取一下当前网址，好从当前网址获取lrc文件    应用于getLrc()和songs[]的音乐列表
let urlIng = window.location.host;
if (urlIng == 'buyaozaikongfushichizaocan.github.io') {
    urlIng = 'http://buyaozaikongfushichizaocan.github.io/qAiJi';// 用http请求，不用考虑https时http失效问题，lrc为开源，也不用考虑安全或被盗问题
} else if (urlIng == 'qaiji.gitee.io') {
    urlIng = 'http://qaiji.gitee.io/q-aiji';
} else if (urlIng.match('127.0.0.1')) {
    urlIng = '';
    localhostTion = true;
} else {
    localhostTion = true;
    console.log('当前url为file://网址，非http,https网址');
}

// 音乐信息
let songs = [
    "宿敌_田人",
    "金琳 - 雨落长安",
    "留什么给你(Live)-孙楠",
    "Two Steps From Hell-Star Sky 活有余罪 - 可有道",
    "最美的瞬间 (女版)_弹棉花的小花",
    "顿啦 爱你（小花版）-弹棉花的小花",
    "郁可唯 - 路过人间",
    "You Don t Know Me - 雅欣",
    "精卫-30年前，50年后",
    "蔡淳佳 - 对不起我爱你",
    "向云端_小霞,海洋Bo",
    "DJ马哥 - 最火OK (DJ版)",
    "别想她_高进",
    "我爱他_王小帅",
    "James Newton Howard - Chase Across DC",
    "Nightwish - Last Ride Of The Day",
    "张佳乐 - 忘记时间 (温柔版)",
    "黄雅莉 - 蝴蝶泉边 (Live)",
    "源辰 - Two Steps From Hell-Star Sky (源辰 Remix)",
    "Dschinghis Khan - Moskau",
    "久石譲 - Mad Summer (疯狂的夏天)",
    "刘大壮 - 会不会 (吉他版)",
    "篝火旁",
    "雨花石",
    "茂茂呀 - 洪荒之力 (越南鼓)",
    "羽·泉、黄征 - 奔跑",
    "金玟岐 - 岁月神偷",
    "馒头 - 胖人愁 (变音版)",
    "雨爱",
    "海来阿木_浮生记",
    "打上花火",
    "Cornfield Chase",
    "Thr rain - 久石譲",
    "Are you OK.m4a",
    /* 歌词添加到这里了 */
    /* === */
    "DJ - 虹之间 (DJ版)",
    "DP龙猪 - 风吹一夏 (片段)",
    "G.G - 给陌生的你听",
    "T.R.Y - 不是因为寂寞才想你",
    "七星 - 佛说",
    "徐秉龙、沈以诚 - 白羊",
    "旺仔小乔 - 剑伤 (片段)",
    "李荣浩、王俊凯 - 李白 (Live)",
    "梁静茹 - 勇气",
    "汪苏泷 - 不分手的恋爱",
    "程响 - 不再联系",
    "筷子兄弟 - 老男孩 (Live)",
    "金玟岐 - 岁月神偷 (Live)",
    /* === */
    "7爷、9爷 - 漫步人生路 (DJ版)",
    "9馨 - Bater Official",
    "Axero - Unity (Extended Mix)",
    "Bear McCreary - Anacreon",
    "Cypis - Gdzie jest biały węgorz",
    "D1ofAquavibe - The Happy Troll",
    "DJ河园 - 青海摇",
    "Doctor Vox - Frontier",
    "Eleonora Gioeni、Angelo Compagnoni、Anna Amato - Paper Sun",
    "Epic Score - Freedom Is Ours (No Vocals)",
    "Feint - My Sunset (我的日落)(Original Mix)",
    "Jam - 七月上",
    "Jarico - Fiery Sky",
    "John Dreamer - Rise (上升 - 史诗音乐)",
    "Kevin MacLeod - Scheming Weasel (faster version)",
    "Leon不太冷的哈哈 - Time Back",
    "MC璐璐 - BATER OFFICIAL",
    "N29 - SADDDDDDDD",
    "Philter - Adventure Time",
    "shankar ehsaan loy - Bum Bum Bole",
    "Sing, R. Sing! - 幼女幻奏",
    "Space - Just Blue (只有蓝色)",
    "SWIN-S - 只因你太美",
    "TAIGA - Middle Of The Night (Extended Mix)",
    "TheFatRat - Xenogenesis",
    "Various Artists",
    "Vexento - Masked Heroes (蒙面英雄)",
    "Waiss ANG、Memo Cash - Dein Weg",
    "刘得柱 - 铿锵有力 (DJ版)",
    "前男友 - 你离开的事实",
    "北筱 - 好好生活 (Remix)",
    "十三叔 - 囧架架 (DJ版)",
    "华语群星 - Super Star (2023青岛大学毕业典礼现场)",
    "吉田潔 - はるかな旅 (远行)",
    "周传雄 - 黄昏 (Live)",
    "坂本昌一郎 - 思い出をありがとう (谢谢你的回忆)",
    "官云康 - 穿越时空的思念",
    "山岡晃 - True",
    "弹吉他的小马哥 - 逃",
    "彭铭 - Asphyxia (窒息)",
    "徐怀钰 - 踏浪 (Live)",
    "搬运工 - Despair (风靡全球版)",
    "文武贝 - 繁华的寂静",
    "新疆美丽公主组合 - 欢乐的跳吧",
    "未知歌手 - 亡灵序曲 (纯音乐)",
    "李代沫 - 这就是爱情",
    "李居居 - 7th Element (完整DJ原版)",
    "李巨儒 - 男孩别哭",
    "杜昊澎 - 青春留白",
    "杨仁清 - 是我一人放不下",
    "林俊杰 - 交换余生 (Live)",
    "林先生 - 没有理由的",
    "氟西汀 - 是想你的声音啊",
    "汪苏泷 - 那个男孩",
    "百石元 - 楽しいねぇ",
    "精彩高迪 - Asphyxi窒息 (治愈)",
    "艾希 - 致你 (女声版)",
    "艾辰 - 你,好不好",
    "许巍 - 旅行 (Live)",
    "许巍 - 曾经的你 (Live)",
    "许巍 - 蓝莲花",
    "金典音乐 - 痴情冢",
    "阿梨粤 - 秒针",
    "黄征 - 你是另一个我",
]

if (localhostTion) {
    songs.push(
        // 更多添加，仅仅用于本地
        "221小伙伴 - 遥远的你 (室友合唱版片段)",
        "24KGoldn、iann dior - Mood (Clean)",
        "A-Lin - 天若有情",
        "Achim Reichel - Aloha Heja He",
        "Adam Clayton、Larry Mullen Jr. - Theme From Mission：Impossible",
        "Against The Current - Legends Never Die",
        "Ahxello - Horizon (地平线)",
        "Alan Walker - Alone",
        "Alan Walker - Fade",
        "Alan Walker - Faded",
        "Alan Walker、Au／Ra、Tomine Harket - Darkside",
        "Alan Walker、Coldplay - Hymn For The Weekend (Remix)",
        "Alan Walker、Noah Cyrus、Digital Farm Animals、Juliander - All Falls Down",
        "Alec Benjamin - Let Me Down Slowly",
        "ALisa - insomnia (治愈版)",
        "ALisa - 木鲸 (治愈版)",
        "ALisa - 风吹过的那个夏天 (治愈版)",
        "ALisa - 鲸落",
        "ALisa、五月的钢琴 - 海 で待っています(我在海边等你) (我在海边等你)(治愈版)",
        "AnDyWuMUSICLAND - Something Just Like This (Megamix)",
        "Anna Leyne、Spada - Catchfire (Sun Sun Sun) (DJ沈木版)",
        "Anna Yvette、Rootkit - Against The Sun",
        "ANU - FLY",
        "Anuo. - 喜欢你 (x0.8)",
        "Aove - 群星-2018 Serato Recording 2（Aove Remix）",
        "Armağan Oruç - Gun Double",
        "Asher Monroe - Here With You",
        "Ashes Remain - On My Own",
        "ATF - Reborn",
        "Audiomachine - Breath And Life (呼吸与生命)",
        "Audiomachine - The New Earth (No Choir)",
        "Austin Mahone、Rich Homie Quan - Send It (网友改编)",
        "Ava Max - My Head & My Heart",
        "Avicii - The Nights (DJ NOXMU版)",
        "Ayo97、周思涵 - 感谢你曾来过",
        "B216_ - 无感 (纯音乐0.8x慢速) (remix)",
        "BachBeats - Super Love",
        "Barcode Brothers - Flute (长笛)(Radio Edit)",
        "Bater official - 迷人的危险",
        "Bater official - 黎明前的黑暗 (女声版)",
        "BeatBrothers - Fight",
        "BEAUZ、Jessie Villa - Little Do You Know",
        "BGM供货商 - 通往胜利 (钢琴版)",
        "BM奈一 - 后继者",
        "BOSS HAN - Miracle BattleTec (DJ版)",
        "BOSS HAN - 搞笑音乐",
        "Brand X Music - Helmet to Helmet (头盔挨着头盔)",
        "Brass Roots - Chachita",
        "Cagnet - 24／7",
        "Calvin Harris、John Newman - Blame",
        "Calypso、DJ Despacito、Échame La Culpa - Despactio",
        "Chiu Chiu、KT杨君涛 - 7538 (Me U-Remix)",
        "Chris Rock、Danny Jacobs - Afro Circus ／ I Like To Move It",
        "Christina Aguilera、A Great Big World、Sebastien - Say Something (Sebastien Remix)",
        "Christine Welch - 一百万个可能 (Live)",
        "Christine Welch - 一百万个可能",
        "Christophe Lebled - Alpha",
        "CHYL - Boom Boom",
        "cici_ - 盗墓笔记·十年人间 (片段)",
        "CNBALLER、DP龙猪、CLOUDWANG 王云 - 全部都是你",
        "CO1 - 一样的月光 (0.8x版)",
        "CO1 - 我看过 (0.8x)",
        "CO1 - 末班车 (0.8x)",
        "CO1 - 给陌生的你听 (0.8x)",
        "Corki - 下坠Falling",
        "Cornfield Chase",
        "Craig David - Insomnia (Up All Night Mix)",
        "Croatia Squad - Drop That Skirt (Radio Mix)",
        "Cuishan He - If You’re Happy",
        "Cypis - Gdzie jest biały węgorz？(Zejśćie) (Explicit)",
        "Damon Empero - I Promise (我承诺)",
        "Dan Farber - Don't Touch (不要触摸)(DJ Mix)",
        "Dancelife Orchestra - Espana cani (Paso Doble ／ 60 BPM)",
        "dancing baby - 真真真的爱 (TV版)",
        "dancing baby - 真真真的爱",
        "Daniel Powter - Free Loop",
        "Daniel Yount - Novera (诺维拉)",
        "Dave Rodgers - DEJA VU (Extended Version)",
        "Dave Rodgers - Déjà Vu",
        "David Guetta、Nicki Minaj、Bebe Rexha、Afrojack - Hey Mama",
        "Devotion - My Prayer",
        "Dirty Palm、Conor Ross、Chandler Blasé、Chandler Blasé - Flowers",
        "DJ Blyatman、Russian Village Boys - Cyka Blyat",
        "DJ HAI CENA - Not the One (不是那个)",
        "DJ Okawari - Luv Letter (情书)",
        "DJ Titus - Epic",
        "DJxia Y、龍先森 - 步步 (-0.8x)",
        "DJ敏少 - 四块五的妞 (咚鼓版)",
        "DJ沈念、承利 - 爱情主演 (咚鼓版)",
        "DJ蚕豆好吃 - Lendo Calendo",
        "DJ铁柱 - 我们的歌 (0.8x片段)",
        "DJ马哥 - C哩C哩",
        "Don Omar、Lucenzo - Danza Kuduro",
        "DoubleC大宝西 - 2.14",
        "DP龙猪 - 风吹一夏 (片段)",
        "Dschinghis Khan - Moskau",
        "dwayne ford - Perseus",
        "ediq - 路过八零",
        "Electronic Arts - Red Alert 3 Theme： Soviet March",
        "Elektronomia - Limitless",
        "en - 可不可以 (片段)",
        "en - 嚣张",
        "Epic Score - Advancing the Troops (推进部队)",
        "Epic Score - Freedom Is Ours (No Vocals)",
        "Epic Score - Full Armor Full Force (全副武装 全力出击)",
        "Epic Score - Liberators (解放者)",
        "Epic Score - Make Your Own Fate",
        "Epic Score - Strike Package Ready (No Vocals)",
        "Epic Score - Time Will Remember Us (时间会记住我们)",
        "Epic Score - You Must Overcome",
        "Eric周兴哲 - 你,好不好？",
        "F-777 - The 7 Seas (七片海)",
        "F.I.R.飞儿乐团 - 你的微笑",
        "F.I.R.飞儿乐团 - 我们的爱",
        "F.O.O.L - Criminals (罪犯)",
        "Fall Out Boy - Immortals",
        "Feint - My Sunset (我的日落)(Original Mix)",
        "Florian Bur - Living",
        "FPX、Chrissy Costanza、Against The Current - PHOENIX",
        "FuGa pang - Lucky",
        "full tilt - Awake",
        "G.E.M.邓紫棋 - 倒数",
        "G.E.M.邓紫棋 - 光年之外",
        "G.E.M.邓紫棋 - 句号",
        "G.E.M.邓紫棋 - 我的秘密",
        "G.E.M.邓紫棋 - 来自天堂的魔鬼",
        "G.E.M.邓紫棋 - 画 (Live Piano Session Ⅱ)",
        "G.G - 小可爱与小领带",
        "G.G - 给陌生的你听",
        "Gamper & Dadoni、Ember Island - Creep",
        "GANK - Resurrection",
        "Gargantuan Music - Fearless (无所畏惧)",
        "Geoff Zanelli - Beyond My Beloved Horizon",
        "GG - 洋葱",
        "ghfhgfyg - 王者荣耀 (口白)",
        "ghfhgfyg - 王者荣耀 (李白版)",
        "Gifty - 戒烟",
        "Glimmer of Blooms - Can't Get You out Of My Head",
        "Globus - Serenata Immortale (最终幻想7)",
        "GTRS - 伊格赛听-谪仙 (DJR7版)",
        "Hans Zimmer - End Credits",
        "Harry George Lightfoot - Rebirth (重生)",
        "hea2t - 恋殇",
        "Henry Jackman - First Class",
        "HINA - Boomerang (回旋镖)",
        "Htikkw - Waka (0.7X)",
        "i5 - 越来越不懂 (0.8x)",
        "Idina Menzel - Let It Go",
        "Imagine Dragons - Natural (Live)",
        "Instrumental Core - Galactic Dust",
        "iw ix - 月光の雲海 (月光下的云海)",
        "J.Boss - Sweetie(Be_Mine)",
        "Jack Stauber - Buttercup",
        "Jacob Tillberg、DEAF KEV - Fade Away (渐行渐远)(Deaf Kev Remix)",
        "James Newton Howard - Chase Across DC",
        "Janji - Horizon (地平线)",
        "January - 나를 위한 여행 (为了我的旅行)",
        "Jason Chen(陈以桐) - Love The Way You Lie",
        "Jason Chen(陈以桐) - We Can't Stop",
        "Jasper Forks - River Flows In You (你的心河)",
        "Jawsh 685 - Laxed (DJ Mountain版)",
        "Jaymes Young - Infinity",
        "Jim Yosef - Link (连接)",
        "John Dreamer - Becoming a Legend (成为一个传奇)",
        "John Dreamer - Rise (上升)",
        "Jon Young - 2 Soon",
        "Jonasu - Black Magic",
        "Jonathan Buchanan - Champions (冠军)",
        "Josh Vietti - A Thousand Miles (千山万水)",
        "July - A cut in Love",
        "July - Love Theme (爱情主题)",
        "July - My Soul (我的灵魂)",
        "Jundada.Music - 俊大大Music当我还在原地为你选择去等待次品无法代替",
        "K-391 - Summertime (夏日时光)",
        "K-391、Alan Walker、Julie Bergan、胜利 - Ignite",
        "K.Williams - 卡农变奏曲",
        "Kaiz、Phúc Du、King Kudo - AKLGD (KAIZ Remix)",
        "Katie Sky - Monsters (MushrooM Remix)",
        "Katie Sky - Monsters",
        "Kenny G - Going Home (纯音乐)",
        "Kevin Rater - I LOVE YOU",
        "kexil - 我怀念的 (0.8x)",
        "Kiiiu_ - 怪咖 (降调版)",
        "Kina、Adriana Proenza - Can We Kiss Forever",
        "Klaus Badelt - He's a Pirate (他是海盗)",
        "Krutikov Music - Enemy (Arcane League of Legends) (宿敌)(Epic Version)",
        "Lady Gaga - Poker Face (Makkur Remix)",
        "LeeAlive - Water (水)(Original Mix)",
        "Lefty Hand Cream - 恋音と雨空 (恋歌与雨天)",
        "Li-2c - 隔岸观火",
        "LIUXY-XY - 女孩 (0.8x片段)",
        "LJY - Autumn (秋).wav",
        "LKer林柯 - 满目星辰皆是你",
        "Ludwig van Beethoven - 命运交响曲",
        "m-taku - Komorebi (叶隙间洒落的阳光)",
        "M.Graveyard - You",
        "MAKE-UP - ペガサス幻想",
        "Mark Petrie - Go Time (出发时间)",
        "Mark.kevin(허야동) - Suspense opening",
        "Maroon 5 - Animals",
        "Martin Garrix、Clinton Kane、Alle Farben - Drown (Alle Farben Remix)",
        "MARUV、BOOSIN - Drunk Groove (Explicit)",
        "Max Brhon - The Future (未来)",
        "MaxRiven - Astronomia (天文学)",
        "MC天子、夏沫MOMO - 不爱又何必纠缠",
        "MC浪子楚阳 - 江海不渡你 (烟嗓版)",
        "MC贱人 - 我们毕业了",
        "MC颖三儿、蔚蓝 - 百家姓",
        "Michael Conn - Pitcairn Story",
        "Michael Forster、Hans Zimmer、alex gibson、Anna Stevens、Ryan Rubin - Cornfield Chase (原野追逐)(Piano-Cello Version)",
        "Michael Hunter - The Theme From San Andreas",
        "Michael Jackson - Billie Jean",
        "Mike Zhou - The Dawn (亡灵序曲完美钢琴版)",
        "MJ-7 - Sorry 对不起",
        "MOMOLAND、CHROMANCE - Wrap Me In Plastic (降调版片段)",
        "MOONBOI(杨望舒)、李开心 - 可不可以给我你的微信",
        "MoreanP - Feeling The Rain",
        "Mountain、LINGDURemix - ltalia e  voi (Remix)",
        "Mr.Polska - Move Up (Lost Gravity)",
        "MuSik I、满舒克、廖伟珊 - My Heart Will Go On(1)",
        "MuSik I、满舒克、廖伟珊 - My Heart Will Go On",
        "Muzikfabrik、Anatoliy Frolov - Leaving (DJ版片段)",
        "Nana、Booya Family - Lonely (2021 Remastered Version)",
        "Nanne Grönvall - Håll om mig",
        "NextRO - Anatomy (解剖)(Original Mix)",
        "Nick.Y - Butterfly",
        "Nicky - 说散就散 (弹唱版)",
        "Nightcore - Heartbeat",
        "Nightwish - Last Of The Wilds (荒野遗孤)",
        "Nightwish - Last Ride Of The Day",
        "Nino学长 - 若之前",
        "Nora En Pure - Lake Arrowhead (箭头湖)(Radio Mix)",
        "Oturans - 潮鸣り (潮鸣)(Remix)",
        "Owl City、Carly Rae Jepsen - Good Time",
        "Pascal Letoublon、Leony! - Friendships (Lost My Love)",
        "Peter Jeremias - Dusk (黄昏)",
        "Peter Roe - Last Reunion (最后的重逢)",
        "Phao、CM1X - Hai Phút Hơn (两分多钟)(Remix)",
        "Philter - Adventure Time (冒险时刻)",
        "Phounius - 風の住む街 (风居住的街道)(钢琴版)",
        "Pianomob（钢琴暴徒） - Flower Dance (钢琴版I)",
        "pluko、pronouncedyea、Egzod - Feel the Fire (Egzod Remix)",
        "Position Music - Man At Arms (重骑兵)",
        "PSY - Gentleman",
        "Ramin Djawadi - Go Big Or Go Extinct",
        "Raphaël Beau - Larrons En Foire",
        "Rauf & Faik - Can't Buy Me Loving ／ La La La",
        "Rauf & Faik - это ли счастье？ (难道这是幸福吗)",
        "Really Slow Motion - Deadwood Main (朽木主题)",
        "Rezz - Edge (边缘)",
        "Richard Clayderman - A Comme Amour (秋日的私语)",
        "Richard Clayderman - Für Elise (致爱丽丝)",
        "Rise - Epic Music (崛起 - 史诗音乐)",
        "Robin Hustin、Jex、TobiMorrow - Light It Up",
        "Rompasso - Angetenar (安捷纳尔)(Subkills Remix)",
        "S.H.E - 不想长大",
        "Sami & Sasha - Love You Like A Love Song",
        "Sand - CHINA-2 (中国-2)",
        "Sara、刘佳 - 爱很美",
        "Sasha Alex Sloan - Dancing With Your Ghost",
        "Seeb、Skylar Grey - Say You Love Me (Clean)",
        "SeVen.13 - Limitless (无限)",
        "Sevenn - Loco Papi",
        "Shake9. - 画心 (0.8) (片段)",
        "Shang、lil sophy - 断线",
        "shankar ehsaan loy - Bum Bum Bole",
        "Shire Music - For Glory",
        "Shire Music - From the Skies",
        "Shire Music、Various Artists - Dark Obsessions",
        "Sia、Alan Walker - Move Your Body (Alan Walker Remix)",
        "Sia、ZAYN - Dusk Till Dawn (DJ愉先生版)",
        "Silver Screen、久升音艺 Silver Screen - Beneath The Horizon",
        "Skan、Krale、Drama B、M.I.M.E - No Glory",
        "Skrillex、Sirah - Bangarang",
        "SLANDER、Dylan Matthew - Love is gone (Justin Dai & Marvin Bootleg) (Marvin Remix)",
        "Slow down. - 江南 (0.8x)",
        "SongLong - 告五人-爱人错过 (0.8x降调)(SongLong remix)",
        "SteveGlen - 震撼大气开场音乐.wav",
        "Steven Burke - Hero's Theme (英雄之魂)",
        "Suprafive、Kelly Clarkson - Catch My Breath (Remix)",
        "T.R.Y - 不是因为寂寞才想你",
        "Taiga - Middle Of The Night (Extended Mix)",
        "Tanir、Tyomcha、Tanir & Tyomcha - Da Da Da",
        "Taylor Swift - Love Story",
        "TFBOYS - 加油!AMIGO",
        "TFBOYS - 宠爱",
        "TFBOYS - 我和2035有个约 (Live)",
        "TFBOYS - 浪花一朵朵 (MV版)",
        "TFBOYS - 青春修炼手册 (Live)",
        "TFBOYS - 魔法城堡",
        "The Glitch Mob、Mako、The Word Alive - RISE",
        "The xx - Intro (前奏)",
        "TheFatRat - Unity (团结)",
        "Thimlife、BibianeZ - Home (Blaze U Remix)",
        "Thomas Bergersen - El Dorado (黄金国)(Dubstep Remix)",
        "Thomas Bergersen - Empire of Angels (天使之城)",
        "Thomas Bergersen - Immortal (不朽)",
        "Tiger JK、Jinsil - Reset (伴奏)",
        "Timmy Trumpet、XING KONG、SAVAGE - Freaks (怪物)(XING KONG When Mom Isn't Home Edit ｜ Bass Boosted)",
        "Tobu - Higher (更高)",
        "Tobu - Life (生活)",
        "Toby Fox - His Theme (他的主题)",
        "Toby Fox - Megalovania (狂妄之人)",
        "Tommo、MELISA - I'm Alone",
        "Tones And I - Dance Monkey",
        "True Strength - Epic Music",
        "TTTony - 为你写诗",
        "Tule、Chris Linton - Fearless Pt. II",
        "Tungevaag、Raaban、Luana Kiara - Bad Boy",
        "Turtles - 빙고 (答对了)",
        "Twins - 莫斯科没有眼泪",
        "Two Steps From Hell - Archangel",
        "Two Steps From Hell - Atlantis",
        "Two Steps From Hell - Disappear",
        "Two Steps From Hell - Dragon Rider (龙骑士)",
        "Two Steps From Hell - For The Win (为了胜)",
        "Two Steps From Hell - Protectors of The Earth",
        "Two Steps From Hell - Resistance Is Fatal",
        "Tăng Duy Tân、BAE - Dạ Vũ (夜舞)",
        "Uu(刘梦妤) - 慢慢",
        "Uu(刘梦妤) - 我要的飞翔 (片段)",
        "Valence - Infinite (无限)",
        "Valentin - A Little Story (一个小故事)",
        "Vanni G - I Say Yeah (DJ蔡萝莉版)",
        "Varien - Future Funk",
        "Various Artists - Collapsing World (崩溃的世界)(Remix)",
        "Various Artists - 斗牛5",
        "Vexento - Anesthesia (麻木)",
        "Vicetone、Cozi Zuehlsdorff - Nevada",
        "Vicetone、Kat Nestel - Angels (Radio Edit)",
        "Vicetone、Tony Igy - Astronomia (天文学)",
        "Virtual Riot - Energy Drink (能量饮料)",
        "Vlado Hudec - Follow Your Dream",
        "W.K. - 逆战 (王者荣耀版)",
        "Waiss ANG、Memo Cash - Dein Weg",
        "WF_Liang - 唯一 (0.8x)",
        "WongKarKwoo - 多幸运 (0.8x)",
        "X-Ray Dog - Hope Always",
        "XXXDAION - 默 (0.8×)",
        "Y2002 - 澜拿蓝 (王者版)",
        "YangYang - 关机又关机",
        "Yiu玥 - 不再联系",
        "Yiu玥 - 老男孩 (Live片段)",
        "Ykey、Namunong - 独行侠 (网友改编)",
        "Yoav Goren - Electric Romeo (电音罗密欧)",
        "Yoav Goren - Tales of the Electric Romeo (电气罗密欧的故事)",
        "Young 7 - 你的前男友",
        "Zealot周星星 - 流离 (片段)",
        "Zedd、Jon Bellion - Beautiful Now",
        "Zeraphym - Lifeline (生命线)",
        "ZheShow - 王者荣耀",
        "Zoë Wees - Control",
        "Zwette、Tom Rosenthal - Go Solo",
        "Zyboy忠宇 - 妈妈的话",
        "Бамбинтон - 3aR",
        "เบลล์ นิภาดา、BOSS HAN - ให้เคอรีมาส่งได้บ่ 泰语童声 (Remix)",
        "ラムジ - PLANET",
        "一杨 - 三生三世",
        "丁可 - If",
        "丁当 - 猜不透",
        "丁译林 - 我们",
        "七元 - IF",
        "七叔(叶泽浩) - 半生雪",
        "七星 - 佛说",
        "万茜、音频怪物 - 为你成全",
        "三亩地 - 城南花已开",
        "三叔说 - 海市蜃楼",
        "三四ve、木槿(余健强) - 甜不辣",
        "不是花火呀 - 不知所措 (片段)",
        "不是花火呀 - 爱人错过 (片段)",
        "不靠谱组合 - 广寒谣",
        "丢丢 - 伤自己",
        "丫蛋蛋(马启涵)、沈虫虫 - 流行歌曲串烧",
        "中央乐团交响乐队 - 春节序曲",
        "丸子呦 - 广寒宫",
        "久石譲 - Mad Summer (疯狂的夏天)",
        "久石譲 - Mother (母亲)",
        "乌兰图雅 - 信天游",
        "乌兰图雅 - 套马杆",
        "乌兰图雅 - 火辣辣的情歌",
        "乌兰图雅、师鹏、沙溢、胡可、云朵、云飞 - 歌舞：点赞新时代 (Live)",
        "乌兰托娅 - 梦高原",
        "乌兰托娅 - 火红的萨日朗",
        "乐池风 - 找朋友",
        "书怡 - 假面舞会 (女声版)",
        "于果 - 侧脸",
        "于溪悦 - 万爱千恩",
        "云朵、刀郎 - 爱是你我(1)",
        "五月天 - 你不是真正的快乐",
        "五月天 - 后来的我们",
        "五月天 - 突然好想你",
        "五月天、陈绮贞 - 私奔到月球",
        "享儿 - 一万个舍不得",
        "亮总 - 只是你太粗心大意忽略了我的感受 (Remix)",
        "今儿真高兴(cover) - 今儿真高兴",
        "今晚打老虎 - 客官不可以 (Live 片段)",
        "付雪 - 金玉良缘",
        "任妙音 - 花千骨",
        "任宇翔 - 稳住别浪 (王者荣耀鬼畜版)",
        "任然 - 凉城",
        "任然 - 山外小楼夜听雨",
        "任然 - 飞鸟和蝉",
        "任立佳、千百顺 - 两个我们2017",
        "任贤齐 - 伤心太平洋",
        "任贤齐 - 心太软",
        "任贤齐、杨千嬅 - 花好月圆夜 (国语版)",
        "伍佰&China Blue - 挪威的森林",
        "伍华 - 伤已成曲",
        "伍华 - 独白式分手",
        "伍思凯 - 特别的爱给特别的你",
        "优秀少年好好 - 可爱小宝贝",
        "伦桑、橙光音乐 - 山有木兮",
        "伯爵Johnny、唐伯虎Annie - 伯虎说",
        "伶伶er - 小鸟伏特加",
        "何文宇 - 不配念旧",
        "何泽远 - 一杯牛奶 (Live)",
        "何炅、王诗龄 - 栀子花开",
        "何野 - 天亮以前说再见",
        "余志坪 - 阿哥阿妹",
        "余超颖 - 勇气 (片段)",
        "你的上好佳 - 白鸽",
        "你郝兄 - 往后余生（不见）",
        "侃侃 - 滴答",
        "依邦妮 - 大猩猩舞 (DJ版)",
        "信乐团 - 死了都要爱",
        "信乐团 - 海阔天空",
        "傅许 - 寂静之空",
        "傅许 - 桜花雨 (樱花雨)",
        "光良 - 童话",
        "全球典藏音乐单 - Mariage d'amour (梦中的婚礼).wav",
        "八三夭乐团 - 想见你想见你想见你",
        "八云轨 - 秒 · 清风",
        "六三四 - 沸き上がる闘志",
        "六哲 - 你给的幸福不是我想要的",
        "六哲 - 多情的人总被无情的伤",
        "六哲 - 如果没有他你还爱我吗",
        "六哲 - 潮流串烧",
        "六哲 - 爱情好无奈(1)",
        "六哲 - 相爱分开都是罪",
        "六哲 - 被伤过的心还可以爱谁",
        "六哲、陈娟儿 - 错错错",
        "六道 - 惊雷",
        "兮有妹 - 梦里梦外都是你",
        "兮沐 - 黄昏之时 (钢琴版)",
        "关喆 - 想你的夜",
        "冠军 - 11 (0.8X)",
        "冠军 - 人鱼的眼泪 (0.8X)",
        "冠军 - 你要的全拿走 (0.7X)",
        "冠军 - 做我的猫 (0.8X)",
        "冯提莫 - 佛系少女",
        "冯晓泉 - 冰糖葫芦",
        "冯靖凯 - 晴天 (片段)",
        "冰冰超人 - 杰出星空",
        "冷漠 - 苦咖啡",
        "冷漠、杨小曼 - 我爱你胜过你爱我",
        "冷雪儿 - 可能否",
        "凤凰传奇 - 全是爱",
        "凤凰传奇 - 天蓝蓝",
        "凤凰传奇 - 感到幸福你就拍拍手",
        "凤凰传奇 - 我从草原来",
        "凤凰传奇 - 我和草原有个约定",
        "凤凰传奇 - 最炫民族风 (广场舞版)",
        "凤凰传奇 - 月亮之上",
        "凤凰传奇 - 等爱的玫瑰",
        "凤凰传奇 - 自由飞翔",
        "凤凰传奇 - 荷塘月色",
        "凤凰传奇 - 郎的诱惑",
        "刀小刀 - Da Da Da (酒吧专用)",
        "刀郎 - 2002年的第一场雪",
        "刀郎 - 冲动的惩罚",
        "刀郎 - 情人",
        "刀郎 - 披着羊皮的狼",
        "刀郎 - 敖包相会",
        "刀郎 - 花儿为什么这样红",
        "刀郎 - 西海情歌",
        "刀郎、云朵 - 十送红军(1)",
        "刘三姐 - 山歌好比春江水",
        "刘亦心(可乐就是力量) - Lover Boy 88 (片段)",
        "刘亦心(可乐就是力量) - 牵丝戏＋虚拟 (片段)",
        "刘佳 - 爱的就是你",
        "刘俊骐 - 好喜欢你",
        "刘和刚 - 父亲",
        "刘嘉亮 - 你到底爱谁",
        "刘增瞳 - 不后悔遇到你",
        "刘大壮 - 偏爱 (片段)",
        "刘大壮 - 做我老婆好不好 (Live片段)",
        "刘大壮 - 再见 (片段)",
        "刘大壮 - 勇气 (Live片段)",
        "刘大壮 - 可惜不是你",
        "刘大壮 - 寂寞沙洲冷 (片段)",
        "刘大壮 - 我不是你的宋冬野 (Live片段)",
        "刘大壮 - 我们终究是错过 (片段)",
        "刘大壮 - 爱不得忘不舍 (片段)",
        "刘大壮 - 珊瑚海 (片段)",
        "刘大壮 - 红色高跟鞋 (片段)",
        "刘大壮 - 说了再见 (片段)",
        "刘大壮 - 这个年纪 (片段)",
        "刘彬濠 - 后来遇见他",
        "刘得柱 - 铿锵有力 (DJ版)",
        "刘德华 - 中国人",
        "刘德华 - 冰雨 (2011上海演唱会现场)",
        "刘德华 - 忘情水",
        "刘德华 - 恭喜发财",
        "刘思奇 - 彩虹",
        "刘思瑶nice - 化形的鱼",
        "刘欢 - 从头再来",
        "刘欢 - 好汉歌",
        "刘欢 - 少年壮志不言愁 2006欢歌上海演唱会",
        "刘欢、陈奕迅 - 菊花台 (Live)",
        "刘玥含 - 小冤家 (俏皮女声版)",
        "刘珂矣 - 半壶纱 (3D环绕版)",
        "刘美麟 - 因为是爱",
        "刘至佳、韩瞳 - 时光背面的我",
        "刘若英 - 为爱痴狂",
        "刘若英 - 后来",
        "刘若英 - 听说",
        "初音ミク、Otomania - Ievan Polkka (Replica ver.)",
        "办桌二人组 - 在心里从此永远有个你",
        "加快版中文网络流行歌曲劲爆串烧 - 2014年12月收录 (DJ版)",
        "动力火车 - 当 (Live)",
        "劫 - 心如止水 (x0.8)",
        "化身复仇者 - 济公1985",
        "北川同学 - 日不落 (片段)",
        "北筱 - 好好生活 (Remix)",
        "十二大美女 - 免失志 (MV版)",
        "千古(Live)--许嵩",
        "半吨兄弟 - 爱就一个字(1)",
        "半吨兄弟 - 爱情错觉(1)",
        "华晨宇、郎朗 - 好想爱这个世界啊 (Live)",
        "华语群星 - 北京欢迎你",
        "华语群星 - 悲伤已成曲",
        "华语群星 - 明天会更好",
        "华语群星 - 杂技：争奇斗技 (Live)",
        "华语群星 - 歌舞：找朋友 (Live)",
        "华语群星 - 水星记 (片段)",
        "华语群星 - 爸爸去哪儿 (改编版片段)(1)",
        "华语群星 - 真心英雄",
        "华语群星 - 舞法天女",
        "卓依婷 - 好人一生平安",
        "南合文斗 - 让泪化作相思雨",
        "南辞、泽亦龙 - 总有一天我会变得特别特别优秀 (第三版)",
        "南辰Music、杨玉环、苏可可 - 如果后来的我们 都已经忘了对方 (片段)",
        "卞卞 - 够钟 (片段)",
        "卢冠廷、莫文蔚 - 一生所爱",
        "卢卢快闭嘴 - 江南 (Live片段)",
        "印子月 - 借过",
        "印子月 - 落空",
        "原来是萝卜丫 - 是心动啊",
        "又又wsy - 可惜没如果 (Live)",
        "古筝萧雅 - 片片相思赋予谁",
        "叫宝宝 - 愿 (Live 片段)",
        "叫宝宝 - 烟花易冷 (片段)",
        "可以喜欢我吗 - 当你走了 (改编版)",
        "叶丽仪 - 上海滩",
        "叶启田 - 爱拼才会赢(1)",
        "叶子 - 吻和泪 (午夜深情版)",
        "叶洛洛 - 小了白了兔",
        "叶洛洛、Babystop_山竹 - 特别关注",
        "叶琼琳、董唧唧 - 爱你 (情话多说一点)(1)",
        "叶翠 - 我的祖国",
        "叶蒨文 - 潇洒走一回",
        "司徒兰芳、赵真 - 闯天涯",
        "吃鸡王者荣耀小仔爷 - 吃鸡王者荣耀小仔爷原声 (片段)",
        "吉他的天空 - 暗里着迷",
        "吉克隽逸 - 歌舞：映山红 (Live)",
        "吉田潔 - はるかな旅 (远行)",
        "吕口口 - 该不该",
        "吕大叶、马子林Broma、陈觅Lynne - 篝火旁",
        "吕继宏、宋祖英 - 九九艳阳天",
        "吕飞、陈星 - 离家的孩子",
        "吴奇隆 - 祝你一路顺风",
        "吴欣怡 - 布谷鸟",
        "吴静 - 女儿情",
        "吸引力合唱组 - 一个师傅仨徒弟",
        "吾尊 - 当你走了",
        "周传雄 - 关不上的窗",
        "周传雄 - 冬天的秘密",
        "周华健 - 朋友",
        "周华健 - 花心",
        "周华健 - 让我欢喜让我忧",
        "周延英（英子-effie） - 回不去的从前",
        "周思涵 - 过客",
        "周杰伦 - 不能说的秘密 (Live)",
        "周杰伦 - 双截棍",
        "周杰伦 - 发如雪",
        "周杰伦 - 告白气球",
        "周杰伦 - 稻香",
        "周杰伦 - 简单爱",
        "周杰伦 - 花海",
        "周杰伦 - 说走就走",
        "周杰伦 - 青花瓷",
        "周深 - 和光同尘",
        "周深 - 大鱼",
        "周琰 - 我始终相信每个人都有独特的美丽",
        "周翊涛、李宏镇、郑人予、许文哲 - 全部都是你 (Live)",
        "周艳鸿 - 嫁人就嫁灰太狼",
        "周资恒、小奶瓶 - 那就晚安 (片段)",
        "周迅 - 身未动,心已远",
        "哒斯！ - 过去的就让它过去吧",
        "唐千云 - 海底",
        "唐古 - 你牛什么牛",
        "唐古 - 孟婆的碗",
        "唐磊 - 丁香花",
        "啊糗 - 无话可说",
        "嘉琪先生、祁念 - 如果爱忘了",
        "嘟比Dubi、匀子 - 好像掉进爱情海里",
        "囍哥 - 光 (片段)",
        "四只烤翅 - 不分手的恋爱 (片段)",
        "四只烤翅 - 耿 (四合院版)",
        "在忠 - 遇到 (DJ梦菲版)",
        "坂本龍一 - Merry Christmas Mr.Lawrence (圣诞快乐,劳伦斯先生)",
        "坂部剛 - 前世の記憶",
        "坠. - 关键词 (女版片段)",
        "夏天Alex - 等我先说 (DJ阿喜版)",
        "夏天Alex - 等我先说",
        "夏婉安 - 奈何桥",
        "多谎话 - 蠢货 (0.8x)",
        "夜光下的扮演者 - 我的歌声里 (0.8x)",
        "大D(DLyn)、驴 - 小毛驴之歌",
        "大壮 - 差一步",
        "大宝软妹、w别丢下甜甜 - 时间的过客",
        "大张伟 - 倍儿爽",
        "大柯 - 喜欢",
        "大柯 - 看透以后",
        "大欢 - 多年以后",
        "大眼睛萱萱 - Bandari-秋天的落叶",
        "大籽 - 白月光与朱砂痣",
        "大籽 - 行星",
        "大籽、Lil E - 放空",
        "天才 - 天龙八部之宿敌 (片段)",
        "天籁天 - 你还是从前的你吗",
        "天龙八部之宿敌--许嵩",
        "太田美知彦 - 万里の長城",
        "央金兰泽 - 爱琴海(1)",
        "奇然 - 花千殇",
        "奡雪 - 骨生花",
        "女王☁ - 铃声多多_清唱《泡沫》为什么难过全都是泡沫只一刹的花火你所有承诺",
        "好多倩 - 熊出没 + 喜洋洋与灰太狼 + 大耳朵图图 + 猪猪侠 + 巴啦啦小魔仙 (片段)",
        "好妹妹 - 不说再见",
        "好想谈恋爱啊 - 喜欢你 (0.8x版)",
        "好想谈恋爱啊 - 戒烟 (0.8x)",
        "如果当时--许嵩",
        "妖蝠 - 来不及说再见",
        "姜奕呈 - 今天你弹弹堂了吗",
        "姜玉阳 - 丢了幸福的猪",
        "姜玉阳 - 回忆总想哭",
        "姜筱虎、Selena Gomez、Marshmello - 红色高跟鞋+Wolves",
        "姜鹏Calm - Lover Boy 88 (Live片段)",
        "姜鹏Calm - 猜不透 (Live片段)",
        "姜鹏Calm - 笑 (片段)",
        "姬神 - 千年の祈り (千年的祈祷)",
        "娃娃 - 漂洋过海来看你",
        "孔柏森 - 我爱他 (片段)",
        "孔柏森 - 洋葱 (Live片段)",
        "孙子涵 - 唐人",
        "孙子涵 - 回忆那么伤",
        "孙悦 - 祝你平安",
        "孙楠 - 为江山",
        "孙楠 - 留什么给你",
        "孙燕姿 - 遇见 (DJ版)",
        "孙语赛、萧全 - 不仅仅是喜欢",
        "孙鹏凯 - 赤伶 (弹唱版)",
        "孟祥龙 - 好心分手 (片段) (Demo)",
        "孟祥龙 - 虚拟 (片段)",
        "孤独诗人 - 渡我不渡她",
        "宇桐非 - 爱上不该爱的人(1)",
        "安小木 - 少年 (男声版)",
        "安平 - 唐僧骑马咚那个咚",
        "安筱冷 - Sexy lady (Original Mix)",
        "安苏羽 - 缺氧",
        "安辞 - 原来占据你内心的人不是我 (cover： 贺一航)",
        "宋孟君 - 对方正在输入",
        "宋孟君 - 彼岸花",
        "宋小睿 - 我和你",
        "宋瑞、韩夜、虞姬、小可 - 给我一瓶可以忘记过去的酒",
        "宋祖英 - 大地飞歌",
        "宋祖英 - 好日子",
        "宋祖英 - 小背篓",
        "宋祖英 - 爱我中华(1)",
        "宋祖英 - 长大后我就成了你",
        "官云康 - 穿越时空的思念",
        "宸荨 - Morsmordre (DJ版)",
        "容中尔甲 - 高原红",
        "容祖儿 - 挥着翅膀的女孩",
        "宿敌(片段)--黎林添娇",
        "宿敌--吴奇隆&许志安",
        "对爱的执念从不是海 - 一样的月光 (0.8x)",
        "对爱的执念从不是海 - 和你 (0.85x)",
        "对爱的执念从不是海 - 带我去找夜生活 (0.8x)",
        "对爱的执念从不是海 - 遗失的心跳 (x0.8)",
        "封茗囧菌 - アイロニ (反语)(Demo)",
        "封茗囧菌 - 童话镇",
        "封茗囧菌 - 越来越不懂",
        "小乐颜 - 天空之城 (说唱版)",
        "小余a - 多幸运 (0.8x)",
        "小倩 - 不配怀念",
        "小可、周资恒、DJ YiXiu - 江归江山归山河归河川归川英雄难过美人 (片段)",
        "小右(陈柯右) - 你是我的女朋友",
        "小咪 - 即兴",
        "小咪 - 我走后 (Live片段)",
        "小团子吖 - 一起走到时间的尽头",
        "小太妹 - 天空之城 (特别版)",
        "小奶瓶 - 欧美旋律 (Remix版)",
        "小婳 - 倒数",
        "小小浩、文博 - 学生时代2",
        "小少焱 - 李太白",
        "小峰峰(陈峰) - 说谎",
        "小峰峰(陈峰) - 足够",
        "小徐酱 - 自我感动都是病态",
        "小易萨克斯 - 风筝误",
        "小曾 - 军中绿花",
        "小杨Remix - 你爱我嘛",
        "小沈阳 - 八戒八戒",
        "小沈阳 - 大笑江湖",
        "小沈阳 - 我只是个传说",
        "小沈阳、邵帅 - 你是人间四月天 (Live)",
        "小洲 - 怀念青春",
        "小洲 - 海阔天空",
        "小洲 - 爱情 (DJ版)(1)",
        "小洲 - 盗心贼",
        "小潘潘(潘柚彤) - 黄梅戏 (流行唱腔版)",
        "小潘潘(潘柚彤)、小峰峰(陈峰) - 学猫叫",
        "小灰灰 - 明天,你好 (cover：牛奶咖啡)",
        "小熊弹吉他 - 灰色轨迹 (吉他版片段)",
        "小甜甜 - 秒针 (女声版)",
        "小眼睛阿旺 - 我们的纪念 (片段)",
        "小蓝背心 - 目及皆是你",
        "小虎队 - 爱",
        "小蜗 - 红尘客栈 (片段)",
        "小阿七 - 不谓侠",
        "小阿七 - 从前说",
        "小鸟伏特加 - 雷霆嘎巴",
        "小鸭子老师 - Cứ Chill Thôi",
        "尤枫 - 醉流年",
        "就是南方凯 - 万拒 (Live片段)",
        "就是南方凯 - 信仰 (片段)",
        "尹昔眠 - 奔赴星空",
        "尹昔眠 - 落在生命里的光",
        "尹昔眠 - 西楼别序 (片段)",
        "展展与罗罗 - 沙漠骆驼",
        "屠洪刚 - 藏龙卧虎",
        "屠洪刚 - 霸王别姬",
        "山水组合 - 你莫走",
        "山鹰组合 - 唐古拉风暴 (DJ版)",
        "岑溪阿祥 - 预谋 (阿祥 Remix)",
        "岛的电饭煲 - 角落 (片段)",
        "崔伟立 - 对面的小姐姐 (DJ何鹏版)",
        "崔伟立 - 酒醉的蝴蝶",
        "崔子格 - 卜卦",
        "川 - 落空 (0.8X)",
        "左宏元、张慧清 - 渡情",
        "巴巴贝 - 侧脸 (片段)",
        "布仁巴雅尔、乌日娜、英格玛 - 吉祥三宝 (国语)",
        "布仁巴雅尔、乌日娜、英格玛、华语群星 - 吉祥三宝 (蒙语)",
        "平生不晚 - 君知否",
        "广东雨神 - 广东爱情故事 (DJ98k、DJ奶小深、DJ沈念版)",
        "庄园 - 嘴巴嘟嘟",
        "庄园 - 都说",
        "庄学忠 - 妹妹你大胆的往前走",
        "庄心妍 - 魔鬼中的天使",
        "庐州月--许嵩",
        "应嘉俐 - 活着viva (女版)",
        "庞龙 - 两只蝴蝶",
        "庞龙 - 兄弟抱一下",
        "康硕Kenny - 喜剧之王 Silent Open (電影喜劇之王原聲)",
        "张也 - 绣荷包",
        "张伟进 - 猴哥",
        "张信哲 - 别怕我伤心",
        "张信哲 - 爱如潮水(1)",
        "张信哲 - 过火",
        "张冬玲 - 花开的时候你就来看我",
        "张卫健 - 把酒狂歌(1)",
        "张宇 - 月亮惹的祸",
        "张宇 - 给你们",
        "张宇 - 雨一直下",
        "张家旺 - 冬天的秘密 (片段)",
        "张家旺 - 给不了你未来",
        "张恺彤、周晋进 - 安眠药",
        "张振宇 - 不要再来伤害我",
        "张振宇 - 别说我的眼泪你无所谓",
        "张明敏 - 我的中国心",
        "张明明 - 千般",
        "张杰 - 他不懂 (Live)",
        "张杰 - 剑心",
        "张杰 - 浩瀚",
        "张杰 - 这,就是爱 (2011全球流行音乐金榜现场)",
        "张杰 - 逆战",
        "张杰、杨颖、李晨、陈赫、王大陆 - 这就是爱",
        "张杰、胡迪、范如臣 - 我们都一样 (Live)",
        "张栋梁 - 当你孤单你会想起谁",
        "张浩泽 - 爱就一个字 (片段)",
        "张燕 - 月亮女儿",
        "张碧晨 - 光的方向",
        "张紫豪 - 可不可以",
        "张紫豪 - 地铁等待",
        "张翰 - 拾忆 (快四版)",
        "张芸京 - 偏爱 (DJ林凉、DJ无毒井野版)",
        "张芸京 - 偏爱",
        "张茗 - 守护",
        "张远 - 嘉宾",
        "张远喆 - 不配做你男朋友",
        "张震岳 - 再见",
        "张韶涵 - 亲爱的，那不是爱情",
        "张韶涵 - 欧若拉",
        "张韶涵 - 淋雨一直走",
        "张韶涵 - 隐形的翅膀",
        "张韶涵、阿云嘎 - 星辰大海 (中国梦·祖国颂2021国庆特别节目现场)",
        "弹吉他的小马哥 - 逃",
        "彭丽丽 - 飞蛾扑火",
        "彭羚 - 囚鸟",
        "彭雨菲 - 超级棒棒糖",
        "很美味 - 东西",
        "徐佳莹 - 最初的记忆",
        "徐怀钰 - 分飞",
        "徐怀钰 - 我是女生",
        "徐怀钰 - 踏浪",
        "徐海俏 - 空",
        "徐真真、黑猫警长Giao哥 - 开心真Giao",
        "徐秉龙 - 千禧 (Live)",
        "徐秉龙、桃十五 - 青柠",
        "徐秉龙、沈以诚 - 白羊",
        "徐良、小凌 - 坏女孩",
        "徐良、小凌 - 客官不可以",
        "徐薇 - 云烟成雨",
        "徐誉滕 - 等一分钟",
        "德干旺姆 - 香巴拉并不遥远",
        "心软 - 九张机 (间奏降调0.8x)",
        "悠悠琴韵 - Illusionary Daytime (钢琴版)",
        "情词尧、李哈哈 - 小女子不才",
        "慕容晓晓 - 爱情买卖(1)",
        "慕容晓晓 - 黄梅戏",
        "慕寒、糖瓷 - 述岚记",
        "慢热的气球 - 在你的身边 (片段)",
        "成龙 - 男儿当自强",
        "成龙、吴京 - 中国",
        "成龙、金喜善 - 美丽的神话",
        "我只有两只耳朵 - 你也没有错",
        "戴羽彤 - 来迟",
        "房东的猫 - 所念皆星河 (Live)",
        "才旦卓玛 - 北京的金山上",
        "才旦卓玛 - 唱支山歌给党听",
        "才旦卓玛 - 在北京的金山上",
        "扎西顿珠 - 康定情歌",
        "承利 - Right Now (降调0.8x)",
        "承利 - Time to Pretend (0.8x)",
        "承利 - 一个人的北京",
        "承利 - 我告诉你什么事最可悲1 (Remix)",
        "承利 - 没有物质的爱情只是一盘沙 (Remix)",
        "承利 - 美人鱼 (0.8x)",
        "承利、苏小纯 - 是我放不下",
        "搬运工 - Despair (风靡全球版)",
        "搬运工 - 反正他都不难受",
        "搬运工 - 每个人的身上都有毛毛",
        "摩登兄弟 - 勇气 (Live)",
        "攀娘、吴石九、扎哥 - 三天不打上房揭瓦 (片段)",
        "文 - 粉太郎-命运 (0.8x)",
        "文氓苏 - 2308",
        "断桥残雪--许嵩",
        "新旭 - 洪荒之力 (钢琴版)",
        "方雅贤 - 遇到",
        "无敌灏克 - Bater official (DJ版)",
        "旧时月色音乐、花千骨、苏清墨 - 书途同归",
        "时代少年团 - 霍元甲 (Live)",
        "旺仔小乔 - 剑伤 (片段)",
        "旺仔小乔 - 我还是 (片段)",
        "明洋 - 好心分手 (DJ版)",
        "明洋 - 离开我你会遇见更好的人 (DJ版)",
        "易安音乐社 - Side By Side",
        "易烊千玺 - 丹青千里",
        "易烊千玺 - 大城小爱 (Live)",
        "星辰 - 后来的我们 (0.8X)",
        "是二智呀 - 修炼爱情 (片段)",
        "是二智呀 - 疑心病 (片段)",
        "昱 - Shots (0.8x)",
        "晚安、误 - 落空 (cover：印子月) (Live)",
        "景甜 - 巧遇安徒生",
        "曲艳娇 - 天亮以前说再见 (片段)",
        "曹泽勇 - 飞",
        "曹珅 - 可不可以给我你的微信",
        "曾惜 - 讲真的",
        "會想起我嗎 - 多远都要在一起 (0.8)",
        "有点焦绿 - 我叫安琪拉",
        "木秦、吉丁Kiddin - 碳酸饮料",
        "未知歌手 - 2010年伤感网络流行歌曲劲爆舞曲串烧 by DJ阿喜 (DJ版)",
        "未知歌手 - 38度6 (苏谭谭)",
        "未知歌手 - Autumn (DJ版)",
        "未知歌手 - Color",
        "未知歌手 - Flower Dance (花之舞)(钢琴版)",
        "未知歌手 - Hand Clap",
        "未知歌手 - Laxed (片段).wav",
        "未知歌手 - May I see U again+I love you 3000 times",
        "未知歌手 - only look at me (降调0.9x)",
        "未知歌手 - Salt (DJ版)",
        "未知歌手 - 一格格 (0.8版片段)",
        "未知歌手 - 一次就好 (DJ版)",
        "未知歌手 - 一次就好 (马丽、DJ Ayao)",
        "未知歌手 - 两只老虎",
        "未知歌手 - 九张机 (Slowed 0.8X)",
        "未知歌手 - 亡灵序曲",
        "未知歌手 - 兰亭序 (0.8版)",
        "未知歌手 - 创作的原声 (片段)",
        "未知歌手 - 即兴",
        "未知歌手 - 可不可以 (改编版片段)",
        "未知歌手 - 可惜没如果 (鼓点版)",
        "未知歌手 - 喜之郎果冻 (鬼畜版片段)",
        "未知歌手 - 四季予你 (0.8版片段)",
        "未知歌手 - 大城小爱 (小黄人版)",
        "未知歌手 - 大话西游 (片段)",
        "未知歌手 - 如果爱忘了 (片段)",
        "未知歌手 - 孟姜女",
        "未知歌手 - 孤雏 (0.8x片段)",
        "未知歌手 - 小仙女你怎么了 (散王孤宸)",
        "未知歌手 - 小妹不跟你 (快四版)",
        "未知歌手 - 少年英雄小哪吒 (纯音乐)",
        "未知歌手 - 往后余生 (3D环绕版)",
        "未知歌手 - 往后余生+盛夏的果实 (DJ蓝雅)",
        "未知歌手 - 我们喵星人就是这么拽 (片段)",
        "未知歌手 - 我愿用我半生年华",
        "未知歌手 - 我的草原我的马 (DJ版片段)",
        "未知歌手 - 我知道 (0.8版)",
        "未知歌手 - 明天过后 (DJ莫小七版)",
        "未知歌手 - 晴 (0.85x)",
        "未知歌手 - 浪漫血液 (0.8版片段)",
        "未知歌手 - 渔舟唱晚",
        "未知歌手 - 爱的好累",
        "未知歌手 - 独忆 (红旗)",
        "未知歌手 - 生僻字 (学生考试版片段)",
        "未知歌手 - 疑心病 (改调版0.7)",
        "未知歌手 - 百听不厌全中文网络流行歌曲慢摇串烧",
        "未知歌手 - 盛夏的果实 (片段)",
        "未知歌手 - 碧波摇篮曲",
        "未知歌手 - 绣荷包",
        "未知歌手 - 罗曼蒂克的爱情 (0.8)",
        "未知歌手 - 说谎 (DJ赵小涣)",
        "未知歌手 - 起风了 (校园版)",
        "未知歌手 - 铃儿响叮当 (改编版片段)",
        "未知歌手 - 龙卷风 (0.8版)",
        "朱添泽 - 等",
        "朱铭捷 - 曾经最美",
        "朴树 - 送别",
        "朴永纯 - 一样的月光 (×0.8)",
        "朴永纯 - 个人简介+百变酒精 (×0.8)",
        "朵儿超甜鸭 - 老六",
        "李丽芬 - 爱江山更爱美人(1)",
        "李代沫 - 这就是爱情",
        "李佩琪 - 改革春风吹满地 (片段)",
        "李佳雨 - 梨花凉",
        "李俊佑、小潘潘(潘柚彤) - 宠坏",
        "李克勤 - 护花使者",
        "李哈哈 - 半壶老酒",
        "李哈哈 - 够我喜欢多年",
        "李哈哈 - 白色桔梗花",
        "李哈哈、沈熙、沈熙 - 花开花落一地伤",
        "李奕铭、炮爷 - 潮汐",
        "李娜 - 女人是老虎",
        "李娜 - 青藏高原",
        "李宇春 - 下个，路口，见 (2014《One Night》公益演唱会)",
        "李宗盛 - 鬼迷心窍",
        "李少白 - 山楂树之恋",
        "李常超（Lao乾妈） - 盗墓笔记·十年人间",
        "李慧珍 - 爱死了昨天(1)",
        "李昕融、樊桐舟、李凯稠 - 你笑起来真好看",
        "李晓杰 - 好姑娘",
        "李森 - 城市套路深 我要回农村",
        "李玲玉 - 妈妈的吻",
        "李玲玉 - 情网",
        "李玲玉 - 祝福",
        "李玲玉 - 粉红色的回忆",
        "李羿慧 - 花开花落",
        "李荣浩 - 爸爸妈妈",
        "李荣浩、王俊凯 - 李白 (Live)",
        "李行亮 - 愿得一人心",
        "李袁杰 - 大天蓬",
        "李袁杰 - 离人愁",
        "李谷一 - 难忘今宵",
        "李里梨 - 南风向北",
        "李鑫ya - 剑伤 (片段)",
        "李鑫ya - 好想爱这个世界啊 (片段)",
        "李鑫ya - 白山茶 (Live片段)",
        "李鑫ya - 这个年纪 (片段)",
        "李鑫ya - 青花瓷 (片段)",
        "李飘飘 - 爱丫爱丫 (男生版)(1)",
        "来一碗老于 - 不败的英雄 (片段)",
        "来一碗老于 - 我好想你 (片段)",
        "来一碗老于 - 我走后 (片段)",
        "来一碗老于 - 曹操 (片段)",
        "来一碗老于 - 爱如潮水 + 即兴 (片段)",
        "来一碗老于 - 芊芊 (片段)",
        "来一碗老于 - 解药 (新版)",
        "来一碗老于 - 那些你很冒险的梦 + 修炼爱情 (片段)",
        "杨亚茹Triste - 当爱在靠近",
        "杨仁清 - 是我一人放不下",
        "杨仁清、苏小纯 - 是我一人放不下",
        "杨光ze - 左肩",
        "杨千嬅 - 处处吻",
        "杨坤 - 空城",
        "杨坤、郭采洁 - 答案 (Live)",
        "杨培安 - 我相信",
        "杨培安 - 爱上你是一个错(1)",
        "杨宗纬、张碧晨 - 凉凉 (Live)",
        "杨小壮 - 一个人挺好",
        "杨小壮 - 孤芳自赏",
        "杨小壮 - 爱情堡垒(1)",
        "杨幂 - 爱的供养(1)",
        "杨庆煌 - 雪中情",
        "杨建桥 - 看月亮爬上来",
        "杨洋 - 微微一笑很倾城",
        "杨烁 - 小草",
        "杨烁 - 让我们荡起双桨",
        "杨硕 - 天下起雨了心情什么颜色 失去你的我 快乐还是(1)",
        "杨硕 - 天下起雨了心情什么颜色 失去你的我 快乐还是",
        "杨硕哥哥 - 天亮以前说再见 (杨硕 remix)",
        "杨胖雨 - 静悄悄 (片段)",
        "杨臣刚 - 大话西游",
        "杨臣刚 - 妹儿爱我 杨臣刚",
        "杨臣刚 - 老鼠爱大米",
        "杨莹 - booty Music",
        "杨阳、想一想、哎呦喂 - 呼噜歌",
        "杨雨柔 - Haru Haru",
        "杨颖、李晨、郑恺、邓超、王祖蓝、陈赫 - 超级英雄 (2015奔跑吧兄弟魅力盛典现场)",
        "杭天琪 - 黄土高坡",
        "极端的杨 - 不要忘记我爱你 (0.8)",
        "林俊呈 - 东西",
        "林俊杰 - 可惜没如果 (Live)",
        "林俊杰 - 她说",
        "林俊杰 - 崇拜 (Live)",
        "林俊杰 - 我还想她",
        "林俊杰 - 曹操",
        "林俊杰 - 江南",
        "林俊杰 - 美人鱼",
        "林俊杰 - 背对背拥抱",
        "林俊杰、蔡卓妍 - 小酒窝 (国语版)",
        "林先生 - 伤感",
        "林啟得 - 醒着醉",
        "林小珂 - 尘埃",
        "林小珂 - 美人画卷",
        "林希儿、精彩明sir、阴兵兄弟 - 千本樱",
        "林志炫 - 单身情歌",
        "林志玲 - 特别设计：绽放 (Live)",
        "林秋楠、龙拳小子组合、RJ - 龙拳小子",
        "林育群 - 蜕变",
        "林达浪 - 不找了 (片段)",
        "林达浪 - 忘记拥抱 (片段)",
        "果味纯氧 - STAY (0.8速)",
        "柠檬心 - 那些年追剧的日子",
        "柯柯柯啊 - 画离弦 (片段)",
        "柯柯柯啊 - 白山茶 (片段)",
        "柳岩 - 男神",
        "柳爽 - 漠河舞厅",
        "柳轻颂 - 舞い落ちる花びら(Fallin' Flower) (飘落的花瓣)(钢琴版)",
        "栀hen - may i see u again (我们还能再见吗)",
        "校长(张驰) - 带你去旅行 (Live)",
        "格格 - 火苗",
        "格格 - 雪莲",
        "桃子啊 - 听闻爱情十有九悲 (片段)",
        "梁咏琪 - 灰姑娘",
        "梁炜️（黄瓜哥） - 新娘嫁人了新郎不是我",
        "梁静茹 - 分手快乐",
        "梁静茹 - 勇气",
        "梁静茹 - 可惜不是你",
        "梁静茹 - 宁夏",
        "梁龙、黄渤、沈腾 - 疯狂的外星人",
        "梅朵 - 如果最先遇到的人是我",
        "梓冷 - 情不知所起一往而深",
        "梦柯 - 李太白",
        "梦柯 - 温柔只给意中人",
        "梦柯 - 菠萝咒",
        "梦然 - 没有你陪伴真的好孤单",
        "樊十三 - 幹物女 (0.8)",
        "樱九 - 画骨成沙",
        "樱木BGM - 怦然心动",
        "欢子 - 为何你对我许下承诺",
        "欢子 - 于心何忍",
        "欢子 - 伤心的时候可以听情歌",
        "欢子 - 得到你的人却得不到你的心",
        "欧翠峰 - 西班牙斗牛士",
        "欧阳耀莹、街道办GDC - 春娇与志明 (DJ版)",
        "欧阳菲菲 - 感恩的心",
        "武昌理工学院合唱 - 我的天空 (高考版)",
        "武聆音雄 - 六脉神剑",
        "武聆音雄 - 天龙八部间奏曲 (片段)",
        "段丽阳 - 小孩的梦",
        "段丽阳 - 爸爸妈妈听我说",
        "段丽阳 - 超级拍档",
        "比莉 - Dear John",
        "毛不易 - 不染",
        "毛不易 - 牧马城市",
        "毛华锋 - 奇迹再现 (DJ J.C.Zhou版)",
        "毛华锋 - 奇迹再现",
        "毛阿敏 - 同一首歌",
        "氟西汀 - 是想你的声音啊 (DJ版)",
        "水木年华 - 一生有你",
        "永彬Ryan.B - 放个大招给你看",
        "江珊 - 梦里水乡",
        "江语晨 - 最后一页",
        "汤潮 - 狼爱上羊",
        "汤潮、小沈阳 - 美了美了",
        "汪峰 - 像梦一样自由",
        "汪峰 - 我爱你中国",
        "汪峰 - 春天里",
        "汪峰 - 飞得更高",
        "汪苏泷 - 不分手的恋爱",
        "汪苏泷 - 那个男孩",
        "汪苏泷、朱元冰 - 选我选我",
        "沈唁 - 一直想着他",
        "沈春阳、小沈阳 - 都要好好的",
        "沈熙 - 凤舞九天",
        "沈绪 - 哪里都是你 (0.8x)",
        "沐泽 - 故事与她 (Remix)",
        "没想到(Live)--许嵩",
        "洋子默 - 下个路口见",
        "洛先生 - 孤城",
        "洛天依 - 哪凉快到哪待着去",
        "洛天依 - 我在东北玩泥巴",
        "洛天依、言和、③① - 秒速五厘米",
        "浙音4811(一个大金意) - 拜拜(1)",
        "浩瀚 - 分手在那个秋天",
        "浪子康 - 没有什么不同 (浪子康Remix)",
        "浪子金 - 拿着青春陪你赌",
        "浪子阿赛、沈晗鸢 - 海棠花下",
        "海伦 - 桥边姑娘",
        "海伦 - 画离弦",
        "海来阿木 - 不过人间",
        "海来阿木 - 你的万水千山",
        "海来阿木 - 孤单的人",
        "海来阿木 - 来跳舞 (国语版)",
        "海来阿木 - 浮生记",
        "海来阿木 - 点歌的人",
        "海来阿木 - 阿果吉曲",
        "海来阿木、阿呷拉古、曲比阿且 - 别知己",
        "海梦 - 千年泪 (0.8x)",
        "海梦 - 红色高跟鞋 (0.8x)",
        "涵の心事. - 先说谎的人 (0.8X)",
        "深七 - 你说别再笑了",
        "深七 - 我们不是情侣",
        "深七 - 死在江南烟雨中",
        "添儿呗 - 互相隐瞒 (片段)",
        "清明雨上--许嵩",
        "清水準一 - Bloom of Youth (风华正茂)",
        "清漪 - 执念",
        "游本昌 - 鞋儿破帽儿破",
        "游鸿明 - 爱我的人和我爱的人(1)",
        "满舒克 - 慢热",
        "漫魚 - 恶作剧 (0.8x)",
        "漫魚 - 新地球 (0.8x)",
        "潘玮柏、张韶涵 - 快乐崇拜",
        "潘玮柏、弦子 - 不得不爱",
        "潘美辰 - 我想有个家",
        "澈子 - 当你被塞班洗脑后 (片段)",
        "澤野弘之、mizuki - aLIEz",
        "火火兔 - 一闪一闪亮晶晶",
        "火箭少女101 - 卡路里",
        "火风 - 大花轿",
        "灵g－你就像我在被子里的舒服 却又像风捉摸不住。 - y2002.m4a",
        "灵空GTech - 皇家萌卫",
        "灼夭、戾格 - 刺客",
        "灿烂 - 魑魅魍魉",
        "烟嗓 - 把我删了吧(1)",
        "烟把儿乐队 - 纸短情长",
        "焦迈奇 - 我的名字",
        "爱吃巧乐兹 - 不再联系 (片段)",
        "爱吃巧乐兹 - 你那么爱她 (片段)",
        "爱吃巧乐兹 - 山海 (合唱版片段)",
        "爱吃巧乐兹 - 年轮 (Live片段)",
        "爱弹琴的涵妹 - 倒数 (Live片段)",
        "牛奶咖啡 - 明天,你好",
        "王二妮 - 山丹丹开花红艳艳",
        "王佳杨 - 孤独",
        "王俊凯 - 我在诛仙逍遥涧",
        "王俊凯 - 至少还有你 (Live)",
        "王俊凯、王源 - 掌声响起来",
        "王力宏、谭维维 - 缘分一道桥",
        "王大毛 - 去年夏天",
        "王妤笑 - 寂寞才说爱",
        "王小帅 - 你是我的玫瑰花",
        "王小帅 - 哭泣站台",
        "王强 - 秋天不回来",
        "王忻辰 - 落差",
        "王忻辰 - 迷失幻境",
        "王忻辰、苏星婕 - 落日与晚风",
        "王新新 - 三年的等待 (DJ秦Sir版)",
        "王晓东 - 合十 (DJ默涵版)",
        "王欣宇 - 拾忆",
        "王沐轩 - 我爱你不问归期 (烟酒嗓版)",
        "王津凯 - 再见 (Live片段)",
        "王源、HENRY刘宪华 - 我想我是海 (Live)",
        "王玖 - 我熬夜在凌晨三点",
        "王琪 - 可可托海的牧羊人",
        "王琪 - 送亲",
        "王笑文 - 耿耿于怀",
        "王茗 - 大眠",
        "王莎莎 - 姐就是女王",
        "王菲 - 传奇",
        "王菲 - 但愿人长久",
        "王菲 - 匆匆那年",
        "王贰浪 - 像鱼",
        "王贰浪 - 爱你(1)",
        "王赫野 - 大风吹",
        "王铭基、刘晔 - 孤海",
        "王键 - 冰吻 (网络版)",
        "王雨桐 - 画皮 (片段)",
        "王雨笙 - May I See U Again (DJ叮当版)",
        "王靖雯 - 不知所措",
        "王靖雯 - 会吗",
        "王靖雯 - 沦陷",
        "王韵壹 - 今生感谢你",
        "玖儿 - 9420",
        "玖月奇迹 - 中国范儿",
        "玖月奇迹 - 踩踩踩",
        "球球、白小白 - 宠爱吖",
        "甜甜、宋烨靓 - 过了很久终于我愿抬头看",
        "田一名 - 给我一首歌的时间",
        "田人 - 宿敌",
        "田震 - 好大一棵树",
        "田馥甄 - 小幸运",
        "田馥甄 - 魔鬼中的天使",
        "男明星 - 不潮不用花钱 (0.8x)",
        "男明星 - 可不可以 (0.8×)",
        "男明星 - 春娇与志明 (0.8x)",
        "男明星 - 起风了 (0.8x)",
        "白一阳 - 忍者时代即将结束 (白一阳 remix)",
        "白小白 - 会不会",
        "白小白 - 爱一个人好难",
        "白小白 - 爱不得忘不舍(1)",
        "百石元 - 猪突猛進",
        "眠 - 多远都要在一起 (0.8x)",
        "矢野立美 - LOVE Theme From TIGA (迪迦的爱情主题曲)",
        "矢野立美 - 遠き呼び声の彼方へ (那来自远方的呼唤)",
        "石仙、张龙、杜支村、谭琳 - 小粽子 (小苹果改编版)",
        "祁岩 - 别等我变了",
        "祁闻冥轩 - 精神有道",
        "祁隆 - 爱的世界只有你(1)",
        "祁隆、乐凡 - 等你等了那么久",
        "祖海 - 为了谁",
        "祖海 - 好运来",
        "祥嘞嘞 - 难却",
        "祺明 - 吃鸡手势舞 (DJ版)",
        "禅颜、一柠吖 - 官方的回答 (好听度版)",
        "私に闻いて风i - 季雨晴空",
        "秋原依 - 错季 (DJ名龙版)",
        "秦晨阳、Lunhui轮回 - 毕业那天(1)",
        "秦海清 - 不如",
        "程佳佳 - 别错过",
        "程佳佳 - 太阳 (咚鼓版)(DJ木亦舟版)",
        "程佳佳 - 好想抱住你",
        "程响 - 不再联系",
        "稳弟 - 稳弟� 「热播咚鼓」我想你是爱我的 我猜你也舍不得",
        "窪田美奈 - Cross The Rainbow (跨越彩虹)",
        "章伟杰 - 我已经爱上你",
        "笑阿 - 让我做你的眼睛 (唱腔版)",
        "笨蛋在嘛 - 心做し (0.8x)",
        "第五个季节 - @第五个季节创作的原声一第五个季节",
        "等什么君(邓寓君) - 关山酒",
        "等什么君(邓寓君) - 冬眠 (片段)",
        "等什么君(邓寓君) - 慕夏",
        "等什么君(邓寓君) - 春庭雪",
        "等什么君(邓寓君) - 赤伶",
        "等什么君(邓寓君) - 辞九门回忆",
        "筷子兄弟 - 小苹果 (2015央视非常星发布现场)",
        "筷子兄弟 - 老男孩 (Live)",
        "简弘亦 - 出卖 (DJ阿所版)",
        "简弘亦 - 出卖",
        "米津玄師 - Lemon",
        "米津玄師、DAOKO - 打上花火",
        "精彩康康 - 别再庸人自扰去关心她",
        "精彩鹤轩 - 空蝉",
        "素颜--许嵩&何曼婷",
        "索朗扎西 - 姑娘我爱你",
        "索朗扎西 - 心爱的姑娘",
        "索朗旺姆 - 北京的金山上",
        "紫陌 - 前度",
        "纪一馨 - Shots (0.8x)",
        "纯音乐 - FAKE LOVE",
        "纯音乐 - Italia e voi (3D环绕版片段) (DJ版)",
        "纯音乐 - rags to rings",
        "纯音乐 - 故郷の原風景",
        "纱琉璃Shelley - 我的一个道姑朋友",
        "纵贯线 - 爱的初体验 (Live)(1)",
        "续集 - 孤单心事 (0.8x)",
        "续集 - 心墙 (0.8x)",
        "缝纫机乐队 - 都选C",
        "网络歌手 - 老公送我夏家三千金 老公",
        "网络歌手 - 耍猴儿 (片段)",
        "罗一四 - 我该怎么说(Anything For U)",
        "罗大佑 - 童年",
        "罗百吉、宝贝 - I Miss You",
        "罗震环 - 我们能不能",
        "罗高丞 - 森林时光 (TV Version)",
        "美味 - 可不可以 (片段)",
        "群星 - Joke+老司机带带我",
        "翟亚楠 - 心中的另一个自己",
        "翟迎新 - 鬼子进村",
        "耀温顺 - La La La (说唱原版)",
        "老狼 - 同桌的你",
        "耿磊、冷小妍 - 卑微的喜欢",
        "肥仔 - 买条街 (片段)",
        "胡66 - 浪人琵琶",
        "胡66 - 空空如也",
        "胡伟立 - 偷功",
        "胡伟立 - 初识太极",
        "胡伟立 - 勇往直前",
        "胡伟立 - 市集",
        "胡力 - 分手以后才知道最珍贵",
        "胡夏 - 如果可以 (DJ豪大大版)",
        "胡夏 - 如果可以",
        "胡夏 - 给我的快乐",
        "胡夏、郁可唯 - 知否知否",
        "胡彦斌 - 不负人间",
        "胡杨林 - 香水有毒",
        "胡雯、宇桐非 - 擦肩而过",
        "航航 - 我最思念的某人",
        "般禅梵唱妙音组 - 大悲咒",
        "般若 - 白鸽",
        "良久哦 - 烟 花 易 冷 (改调×0.7)",
        "艾一 - 我们不一样",
        "艾热AIR、JelloRio李佳隆 - 星球坠落 (Live)",
        "艾辰 - 为你写诗",
        "艾辰 - 你,好不好",
        "艾辰 - 归还",
        "艾辰 - 桃花凉",
        "艾辰 - 盗将行",
        "花僮 - 公子向北走",
        "花僮 - 最天使",
        "花僮 - 浪子闲话",
        "花儿乐队 - 化蝶飞",
        "花姐 - 狂浪",
        "花粥 - 归去来兮",
        "花粥、王胜娚 - 出山",
        "花粥、马雨阳 - 盗将行",
        "苏三 - 很任性相爱过",
        "苏以北 - 我走后",
        "苏冬涛 - 你是我未曾拥有无法捕捉的亲昵 (DJ8先生版)",
        "苏打绿 - 小情歌",
        "苏星婕 - 风吹过八千里",
        "苏晗 - 寂寞沙洲冷",
        "苏有朋 - 背包",
        "苏泽 - 脚艺人 (DJ版)",
        "苏琛 - 拾忆 (伴奏)",
        "苏芮 - 奉献",
        "苏芮 - 跟着感觉走",
        "苏贝贝 - 还无法忘记",
        "苏静 - 沉稳总在爱意里翻船",
        "英雄联盟 - 涅槃 (Phoenix)",
        "茂茂呀 - 洪荒之力 (越南鼓)",
        "范倪Liu - 南半球与北海道",
        "范小蛙 - 会长大的幸福",
        "草蜢 - 失恋阵线联盟",
        "草蜢 - 宝贝，对不起",
        "药材 - 几度梦回大唐 (王者荣耀版)",
        "莎莎 - Remember Our Summer (小提琴版)",
        "莫叫姐姐 - 不该用情 (女声版)",
        "莫叫姐姐 - 你能不能不要离开我 (莫叫语版)",
        "莫叫姐姐 - 当我娶过她",
        "莫叫弟弟 - 爱囚(1)",
        "莫文蔚 - 爱",
        "萌小新、李哈哈 - 萝莉哭了",
        "萌萌哒天团 - 咖喱咖喱",
        "萌萌哒天团 - 帝都",
        "萧亚轩 - 最熟悉的陌生人",
        "萧亮 - 梦的过客",
        "萧全 - 海草舞",
        "萧全 - 社会摇",
        "萨顶顶 - 左手指月 (Live)",
        "葛雨晴 - 夜车",
        "葛顺 - Tears",
        "葛顺 - 一个人的浪漫",
        "董丫丫 - 说谎 (片段)",
        "蒋先生、DJ阿金、李安芳 - DA DA DA",
        "蒋大为 - 送别",
        "蒋欣 - 一时间",
        "蒋欣妤 - 追梦",
        "蒋蒋 - 残雪",
        "蒋蒋 - 退",
        "蒋雪儿、七叔(叶泽浩) - 莫问归期",
        "蒋龙 - 行者",
        "蓝心羽 - 寂寞烟火 (片段)",
        "蓝心羽 - 小宇 (片段)",
        "蓝心羽 - 来不及 (片段)",
        "蓝心羽 - 落 (片段)",
        "蓝馨馨 - 我是否也在你心中",
        "蔡依林 - 日不落",
        "蔡健雅 - Letting Go. (0.8变速版)",
        "蔡文姬、澜 - Cheap Thrills (二胡版)",
        "蔡淳佳 - 对不起我爱你",
        "蔡耀轩 - 去年夏天 (咚鼓版)",
        "蔡舜禹、张一末（灰老板） - 断念",
        "蔡黄汝 - 迷人的危险",
        "薛之谦 - 丑八怪+演员 (Live)",
        "薛之谦 - 丑八怪",
        "薛之谦 - 你还要我怎样",
        "薛之谦 - 刚刚好",
        "薛之谦 - 演员",
        "薛之谦 - 独角戏 (Live)",
        "薛之谦 - 认真的雪",
        "藤竹京 - 孤独 (片段)",
        "藤竹京 - 庸人自扰 (片段)",
        "蘑菇头 - 我的将军啊 (考试版)",
        "虎二 - 你应该很快乐",
        "虎二 - 跨不过的距离",
        "虞姬、圈妹、苏可可 - Ealy ng Dea (DJ版)",
        "蜜雪冰城 - 蜜雪冰城主题曲 (官方版)",
        "街道办GDC、欧阳耀莹 - 春娇与志明",
        "西洛卡 - 纪念",
        "西海岸(ACT.1-ACT.7) - westcoast",
        "西游记 - 搞笑 (唐僧跑妞)",
        "要不要买菜 - 全是爱 (片段)",
        "要不要买菜 - 多情种",
        "警长最帅哦 - 我太笨 (0.8x片段)",
        "许冠杰 - 沧海一声笑",
        "许冠杰 - 阿郎恋曲",
        "许华升 - 无法证明 (改编版)",
        "许哲珮 - 气球",
        "许嵩 - 多余的解释",
        "许嵩 - 幻听",
        "许嵩 - 庐州月",
        "许嵩 - 断桥残雪",
        "许巍 - 像风一样自由",
        "许巍 - 曾经的你 (Live)",
        "许巍 - 蓝莲花 (DJ版)",
        "许巍 - 蓝莲花",
        "许茹芸 - 不爱我放了我",
        "许镜清 - 逍遥自在的孙大圣",
        "许镜清、叶矛 - 无底船歌",
        "诗人凉 - 白色桔梗花",
        "说者瑞泽 - 再见王者荣耀2",
        "谢军 - 碎心石",
        "谭晶 - 唐韵",
        "谭艳 - 光明",
        "豆包 - 此生过半 (DJ阿卓版)",
        "豪大大、浪子康 - 这就是爱情 (DJ浪子康、DJ豪大大版)",
        "贝瓦儿歌 - 茉莉花",
        "贵州小蓉儿 - 爱情一阵风(1)",
        "费玉清 - 一剪梅",
        "费翔 - 冬天里的一把火",
        "费翔 - 故乡的云",
        "贾乃亮 - 炽热的青春",
        "贾玲、刘维 - 感觉自己萌萌哒",
        "贾青 - 傻得可以",
        "赖仔Morris - 非酋",
        "赵丽颖 - 十年",
        "赵乃吉 - 曾经你说",
        "赵亦笙 - 你会快乐么",
        "赵传 - 我是一只小小鸟",
        "赵俊铭 - 鲸落WF End (钢琴版片段)",
        "赵俊飞 - 抽烟只抽煊赫门",
        "赵咏华 - 最浪漫的事",
        "赵季平 - 王进打高俅",
        "赵方婧 - 尽头",
        "赵炘屿、柒月 - 有点甜",
        "赵照 - 当你老了 (2012版)",
        "赵雷 - 成都",
        "赵马熙汝 - 喜欢你 (翻唱版)",
        "跟风超人 - 你打不过我吧",
        "路飞仙贝 - 欧若拉",
        "軍 - 喜欢你",
        "转鹿 - Crazy Dave IN-GAME.wav",
        "迪克牛仔 - 有多少爱可以重来",
        "逆时针向 - Asphyxia",
        "逸霄 - 察觉",
        "邓丽君 - 何日君再来",
        "邓丽君 - 路边的野花不要采",
        "邓丽君 - 高山青",
        "邓壬鑫 - 告白之夜 (治愈版)",
        "邓超 - 无敌",
        "邓超、佟大为、黄晓明 - 光阴的故事",
        "邓超、李晨、陈赫、郑恺、鹿晗、王祖蓝 - 超级英雄 (Live)",
        "那英 - 一笑而过",
        "那英 - 三生三世十里桃花",
        "那英 - 征服",
        "邰正宵 - 九百九十九朵玫瑰",
        "邰正宵 - 欲擒故纵",
        "邵雨涵 - 拉拉爱",
        "郁可唯 - 像小时候一样",
        "郁可唯 - 夙念",
        "郁可唯 - 路过人间",
        "郁钧剑 - 沂蒙山好风光",
        "郑伊健 - 虫儿飞 (聂风版)",
        "郑智化 - 星星点灯",
        "郑智化 - 水手",
        "郑源 - 一万个理由",
        "郑源 - 不要在我寂寞的时候说爱我",
        "郑源 - 包容 (Live)",
        "郑源 - 当我孤独的时候还可以抱着你",
        "郑源 - 怎么会狠心伤害我",
        "郑源 - 爱情码头(1)",
        "郑源 - 爱过的人",
        "郑源 - 等",
        "郭玲、冷漠 - 迷茫的爱",
        "郭美美 - 不怕不怕",
        "郭聪明 - 你会遇见更好的人",
        "郭顶 - 我们俩",
        "酉阳美人 - 迷雾散尽一切终于变清晰",
        "醉影An、谣君 - 小巷酒馆",
        "野小马 - 可不可以 (改编版片段)",
        "野小马 - 当真",
        "金久哲 - 干就完了",
        "金伶 - 斯卡布罗集市 (英文版)",
        "金志文 - 远走高飞",
        "金润吉 - Love Love",
        "金玟岐 - 岁月神偷 (Live)",
        "金琳 - 雨落长安",
        "金贵晟 - 虹之间",
        "铃声 - 哦拉拉",
        "银临、Aki阿杰 - 牵丝戏",
        "锋锋 - 囍啊囍 (绿茶版)",
        "锦零 - 恋爱画板",
        "锦零 - 豆花之歌",
        "锦零、凤九 - 文爱",
        "门丽、胡小宝 - 哥哥妹妹",
        "闻人听書_ - 美人画卷",
        "阎维文 - 一二三四歌",
        "阎维文 - 打靶归来",
        "队长 - 哪里都是你",
        "阮言Ruany - 琉璃 (片段)",
        "阮豆 - 小永远",
        "阮豆 - 想要你知道",
        "阮豆 - 马德里不思议",
        "阿冗 - 你的答案",
        "阿冗 - 别想她 (片段)",
        "阿吉太组合 - 阿衣莫",
        "阿妹啊 - 放开手 (片段)",
        "阿宝 - 山丹丹开花红艳艳",
        "阿悠悠 - 你若三冬",
        "阿悠悠 - 旧梦一场",
        "阿杜 - 撕夜",
        "阿桑 - 寂寞在唱歌",
        "阿牛 - 桃花朵朵开",
        "阿禹ayy - 盗墓笔记·十年人间 (片段)",
        "阿细 - 高山低谷 (片段)",
        "阿翔班长 - 烟火里的尘埃 (cover： 华晨宇｜宿涵)(Live)",
        "阿里郎 - 隔壁泰山",
        "阿龙正罡 - 从此我该怎么过",
        "陆嘉诚 - 像我这样的人",
        "陈丙、林泽、伍便滋 - 吃鸡神曲98K (Remix)",
        "陈依梦 - 忘情果 (伤感女声版)",
        "陈同学 - 生僻字",
        "陈奕迅 - 十年",
        "陈奕迅 - 单车",
        "陈奕迅 - 好久不见",
        "陈奕迅 - 孤勇者",
        "陈奕迅 - 浮夸",
        "陈奕迅 - 红玫瑰",
        "陈奕迅、王菲 - 因为爱情",
        "陈子晴 - 第二星空",
        "陈学冬 - 不再见",
        "陈少华 - 九九女儿红",
        "陈少华 - 九月九的酒",
        "陈慧琳 - 记事本",
        "陈文非 - 孤独颂歌",
        "陈旭 - 哥只是个传说",
        "陈明 - 快乐老家",
        "陈星 - 流浪歌",
        "陈柏宇 - 你满我满 (DJ版)",
        "陈楚生 - 有没有人告诉你 (3D环绕版)",
        "陈泫孝(大泫) - 静悄悄",
        "陈洁丽 - 猪猪侠",
        "陈涓 - 相见难别亦难",
        "陈玉建 - 偷偷的哭",
        "陈瑞 - 白狐",
        "陈红 - 常回家看看",
        "陈逗逗 - 简单点",
        "陈雅森 - 温柔乡",
        "陈雅森 - 问天问地问自己",
        "陈雪凝 - 你的酒馆对我打了烊",
        "陈雪凝 - 假装",
        "陈雪凝 - 愚昧",
        "陈雪凝 - 欧巴我不傻 (片段)",
        "陈雪凝 - 淋雨一直走+说爱你+可不可以给我你的微信 (Live)",
        "陈雪凝 - 绿色",
        "降央卓玛 - 美丽的草原我的家",
        "隔壁老樊 - 一个人想着一个人 (片段)",
        "隔壁老樊 - 多想在平庸的生活拥抱你 (Live)",
        "隔壁老樊 - 大眠 (片段)",
        "雅俗共赏--许嵩",
        "雅欣 - You Don t Know Me",
        "雨宗林 - 那一刻",
        "雪二 - 可不可以 (改编版)",
        "零柒 - 九张机 (王者荣耀版)",
        "霍建华、赵丽颖 - 不可说",
        "青春美少女 - HAPPY Baby",
        "青海龙泽 - 山楂啊梨啊",
        "青蛙乐队 - 小跳蛙",
        "青鸟飞鱼 - 此生不换",
        "面具锋 - 霸王别姬",
        "鞠文娴 - BINGBIAN病变 (女声版)",
        "韦康 - Breathe",
        "韩ye - Dancing With Your Ghost (Remix)",
        "韩可可 - 错位时空 (女版)",
        "韩安旭 - 不在",
        "韩安旭 - 多幸运",
        "韩宝仪 - 你潇洒我漂亮",
        "韩文轩 - 佳人轻抚桃花扇",
        "韩涪睇的love - 下个，路口，见 (0.8%降调)",
        "韩磊 - 向天再借五百年",
        "韩红 - 天亮了 (Live)",
        "韩红 - 天路 (传统版)",
        "韩红 - 祖国不会忘记",
        "韩红 - 青藏高原",
        "韩雪、刘敏涛、万茜 - 红色高跟鞋 (Live)",
        "音乐之声-SongTaste - Micmacs A La Gare",
        "音阙诗听 - 红昭愿",
        "音阙诗听、王梓钰 - 大雪",
        "音阙诗听、赵方婧 - 芒种",
        "顾嘉辉 - Mark's Theme",
        "顾小柒 - 怕的不是等 是等不到",
        "顾峰 - 犯错",
        "顾峰、斯琴高丽 - 猜",
        "颖儿 - 他们",
        "颜小健 - 一不小心",
        "风起词 - 玫瑰少年 (小提琴版)",
        "饶天亮 - 做你的爱人",
        "馅儿、汤汤不理 - 出山",
        "馒头 - 123喝热水 (Live片段)",
        "馒头 - 38度6",
        "馒头 - 两只野狗在恋爱",
        "馒头 - 你是我的平底锅",
        "馒头 - 你的酒馆为我烤了羊,我就当酒馆的老板娘 (DJ长音频)",
        "馒头 - 加薪歌",
        "馒头 - 变态单身狗",
        "馒头 - 可不可以 (假日版)",
        "馒头 - 吃的是啥东西",
        "馒头 - 嘤嘤嘤",
        "馒头 - 在人间扎心歌",
        "馒头 - 大哥大姐如果你要骂我就请这样骂",
        "馒头 - 大家好，给大家介绍一下",
        "馒头 - 妈妈再打我一次",
        "馒头 - 小屁孩你快走开",
        "馒头 - 我妈已经三天没有打我了",
        "馒头 - 我是一条酸菜鱼",
        "馒头 - 我是不是你最疼爱的人，你为什么不打钱",
        "馒头 - 我的对象啊",
        "馒头 - 挂科版凉凉 (《凉凉》改编版)",
        "馒头 - 撸串之歌",
        "馒头 - 旅行青蛙好害怕",
        "馒头 - 最炫猪肉风",
        "馒头 - 期末之歌",
        "馒头 - 沙漠骆驼 (馒头版)",
        "馒头 - 浪里个浪",
        "馒头 - 灭霸之歌",
        "馒头 - 生僻字",
        "馒头 - 画个圈圈祝福你",
        "馒头 - 红昭愿 (知否版)",
        "馒头 - 肥宅快乐歌",
        "馒头 - 胖人愁 (变音版)",
        "馒头 - 胖胖之歌",
        "馒头 - 胖胖的白羊",
        "馒头 - 苏大强之歌",
        "馒头 - 鬼才会想起",
        "香香 - 就算没有如果",
        "马可 - 两生缘",
        "马天宇 - 该死的温柔",
        "马小马 - 下个，路口，见 (0.8x)",
        "马懿霄 - 不再打扰你",
        "马良、孙茜茹 - 往后余生",
        "高安、杭娇 - 一生无悔",
        "高安、黑鸭子组合 - 红尘情歌",
        "高胜美 - 恋曲1990",
        "高胜美 - 青青河边草",
        "高胜美 - 风飞沙",
        "高进 - 伤心的歌",
        "高进 - 别想她",
        "高进 - 正义之道 (Live)",
        "高进、小沈阳 - 我的好兄弟",
        "高进、李玉刚 - 刚好遇见你 (Live)",
        "高迪 - 黑暗萝莉",
        "高鱼 - 什么样的爱情 (片段)",
        "鬼岛、MC演绎超 - 我的天空 (DJ版)",
        "魏小然 - 几度梦回大唐",
        "魏小然 - 让我做你的眼睛",
        "魏新雨 - 丹青古寨",
        "魏新雨 - 百花香",
        "鱼多余 - 剑魂 (DJ版)",
        "鱼大仙儿 - 我曾",
        "鱼闪闪BLING - 沉醉的青丝 (Live片段)",
        "鲍比达、黄霑 - 定情",
        "鸾音社 - 隔岸",
        "鹏泊 - 啷个哩个啷",
        "鹏鹏、杨小壮 - 口是心非",
        "鹿晗 - 勋章",
        "麦振鸿 - 一心修仙 (纯音乐)",
        "麦振鸿 - 七分伤 (纯音乐)",
        "麦振鸿 - 为她而活 (纯音乐)",
        "麦振鸿 - 乐天派 (纯音乐)",
        "麦振鸿 - 五上仙 (纯音乐)",
        "麦振鸿 - 倒大霉 (纯音乐)",
        "麦振鸿 - 天水滴 (纯音乐)",
        "麦振鸿 - 异香 (纯音乐)",
        "麦振鸿 - 念难断 (纯音乐)",
        "麦振鸿 - 恩断情绝 (纯音乐)",
        "麦振鸿 - 戒情 (纯音乐)",
        "麦振鸿 - 曾经拥有 (纯音乐)",
        "麦振鸿 - 牵绊一生 (不可说) (纯音乐)",
        "麦振鸿 - 疤痕 (纯音乐)",
        "麦振鸿 - 痴颜 (纯音乐)",
        "麦振鸿 - 知晓万里 (纯音乐)",
        "麦振鸿 - 美人的吻 (痴颜) (纯音乐)",
        "麦振鸿 - 遵从本心 (纯音乐)",
        "麦振鸿 - 长留山 (纯音乐)",
        "麦振鸿 - 非礼勿视 (纯音乐)",
        "麦振鸿、罗坚 - 天下第一",
        "麻雀音乐人 - 此地无银二百两",
        "黄依玲 - 只对你有感觉",
        "黄品源 - 你怎么舍得我难过",
        "黄品源 - 海浪",
        "黄国俊 - 真爱你的云",
        "黄圣依 - 只要为你活一天",
        "黄安 - 东南西北风",
        "黄宏、魏宗万、徐玉琨 - 弹棉花 (TV版)",
        "黄征、羽·泉 - 奔跑",
        "黄英华 - Opening",
        "黄诗佳 - 樱花草",
        "黄雅莉 - 蝴蝶泉边",
        "黄霑 - 傲气傲笑万重浪 (终曲)",
        "黄霑 - 男儿当自强",
        "黄霑、罗大佑、徐克 - 沧海一声笑",
        "黄飞鸿 - 拾忆",
        "黄鹤翔 - 九妹",
        "黄龄 - High歌",
        "黄龄 - 痒",
        "黎允文 - 赵子龙",
        "黎耀辉 - IF YOU (0.8X)",
        "黑猫 - 九张机",
        "黑龙 - 38度6",
        "黑龙 - 我爱你你却爱着他",
        "齐会超 - 爱了给了伤了痛了(1)",
        "齐秦 - 外面的世界",
        "齐秦 - 大约在冬季",
        "龍猛寺寬度 - 武家坡 (网友改编)",
        "龙梅子、海彪 - 寂寞的人伤心的歌",
        "龙梅子、王强 - 你把爱情给了谁",
        "龙梅子、老猫 - 漂亮的姑娘就要嫁人啦",
        "龙梅子、老猫 - 爱情专属权(1)",
        "龚玥 - 爱情海(1)",
    )
} else {
    console.log('非本地预览');
}

// 向页面输出音乐数量
document.getElementById('mlength').innerText = songs.length;

function listupdate() {
    // 遍历、输出列表
    let index2;
    for (let index = 0; index < songs.length; index++) {
        if (title.innerText == songs[index]) {
            index2 = index + 1;
            // 设置正在播放的歌曲列表样式
            musicList.getElementsByTagName('div')[index + 1].classList.add('musliIng')
        } else {
            // 恢复其它的样式
            musicList.getElementsByTagName('div')[index + 1].classList.remove('musliIng')
        }
    }
}

setTimeout(() => {
    listupdate()
}, 0);

// 遍历、输出列表
let musicList = document.getElementById('musicList');
let index2;
for (let index = 0; index < songs.length; index++) {
    index2 = index + 1;
    let obect = '<div id="' + songs[index] + '" style="cursor: pointer;" title="' + songs[index] + '" onclick="listonclick(' + index + ')">      <span class="musicItem">' + index2 + '.</span> ' + songs[index] + '</div>';
    musicList.insertAdjacentHTML('beforeend', obect);
}

// 列表点击
function listonclick(index) {
    if (songIndex == index) {
        if (audio.paused) {
            playSong();
            // tanChuang('当前歌曲正在播放，可以点击进度条设置音乐进度');
        } else {
            pauseSong()
        }
    } else {
        // 点击后设置一下当前播放音乐的index，不然songindex还是之前的，到下一首就会以之前播放的音乐为下一首跳转
        songIndex = index;
        loadSong(songs[index]);
        playSong();
    }
}

// 标题点击
function musicTitleOnclick() {
    let musicTitle = document.getElementById('title');
    musicTitle.addEventListener = '<a href="' + musicTitle.innerText + '"></a>';
}

let ind = 0
// 音乐加载错误
function MusicError() {
    if (ind < 3) {
        audio.src = `music/localhost/${title.innerText}.mp3`
        ind += 1
        playSong()
    } else {
        console.error('音乐播放错误');
        nextSong()
        ind = 0
    }
}

// 默认从第一首开始
let songIndex = 0;
// 更新歌曲细节
function loadSong(song) {
    title.innerHTML = song
    audio.src = `music/${song}.mp3`;
    musicCover.src = `images/audio/${song}.png`;
}

// 图片加载错误设置
function musicimgerr() {
    musicCover.src = './images/audio/error.png'
}

// 点击后跳转当前播放个音乐列表
document.querySelector('#mlength').onclick = function () {
    document.querySelector('.musliIng').scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' })// behavior如何滚动，除了smooth其它的都是瞬间。block垂直对齐。inline水平对齐nearest是默认值
}

// 播放歌曲
function playSong() {
    // 元素添加类名
    musicContainer.classList.add("play");
    playBtn.querySelector('i.fas').classList.remove('fa-play');
    playBtn.querySelector('i.fas').classList.add('fa-pause');

    audio.play();

    // 如果因为错误暂停就自动下一首
    if (title.innerText == '已暂停') {
        nextSong();
    }

    listupdate()
}

// 停止播放
function pauseSong() {
    musicContainer.classList.remove('play');
    playBtn.querySelector('i.fas').classList.add('fa-play');
    playBtn.querySelector('i.fas').classList.remove('fa-pause');

    audio.pause();
}

// 上一首
function prevSong() {
    songIndex--
    if (songIndex < 0) {
        songIndex = songs.length - 1
    }
    // 加载歌曲信息并播放
    loadSong(songs[songIndex])
    playSong()
    lrc.style.transform = `translateY(10px)`;

    listupdate()
}
// 下一首
function nextSong() {
    songIndex++;

    if (songIndex > songs.length - 1) {
        songIndex = 0;
    }

    loadSong(songs[songIndex]);
    playSong();
    lrc.style.transform = `translateY(10px)`;

    listupdate()
}

// 创建一个MutationObserver实例
const observer = new MutationObserver((mutationsList) => {
    for (let mutation of mutationsList) {
        if (mutation.type === 'attributes' && mutation.attributeName === 'src') {
            // src属性发生变化时的处理逻辑
            getLrc(title.innerText)
        }
    }
});
// 配置观察选项
const config = { attributes: true };
/**
 * 开始观察
 * @param {HTMLElement} audio 要监听audio元素
 * @param {const} 配置项
 * @returns {none} 无返回
 */
observer.observe(audio, config);

let lrcContent
// 歌词存储object
let lrc = document.querySelector('#lrc')
var lrcNone = false
/**
 * 歌词获取
 * @param {string} titC 歌词名称
 * @returns {none} 无返回
 */
function getLrc(titC) {
    lrc.innerHTML = '加载中...'
    switch (titC) {
        case
            "Cornfield Chase",
            "DJ马哥 - 最火OK (DJ版)",
            "James Newton Howard - Chase Across DC",
            "Thr rain - 久石譲",
            "源辰 - Two Steps From Hell-Star Sky (源辰 Remix)",
            "久石譲 - Mad Summer (疯狂的夏天)",
            "茂茂呀 - 洪荒之力 (越南鼓)"
            :
            lrc.innerHTML = '<span style="background: linear-gradient(-3deg,#eebd89 0%,#d13abd 100%);-webkit-background-clip: text;color: transparent;font-size: 20px;">纯音乐 请欣赏</span>'
            lrcNone = true
            break;

        default:
            lrcNone = false
            $.get(`${urlIng}/music/lrc/${titC}.lrc`, function (data) {
                lrcContent = data
                parseLrc()
            }).fail(function () {
                lrcContent = `
[00:00.00]${titC}
[00:03.00]歌词加载错误或暂无歌词
[00:20.00]请等待更新或投稿对应歌词
`
                parseLrc()
            });
            break;
    }
}
getLrc(title.innerText)

// 容器高度
var containerHeight = document.querySelector('.container').clientHeight;
var lrcData// = parseLrc();
/**
 * 解析歌词字符串
 * 得到一个歌词对象的数组
 * 每个歌词对象:
 * {time:开始时间, words:歌词内容}
 * @returns {object} result 最终返回一个歌词对象数组
 */
function parseLrc() {
    if (lrcNone == false) {
        if (lrcContent) {
            var lines = lrcContent.split("\n")
            /**
             * 最终的歌词对象数组
            */
            var result = [];
            for (var i = 0; i < lines.length; i++) {
                var str = lines[i];
                var parts = str.split(']');
                var timeStr = parts[0].substring(1);// 切割第一个字符也就是这里的[
                var obj = {
                    time: parseTime(timeStr),
                    words: parts[1]
                }
                result.push(obj)
            }
            lrcData = result
            createLrcElements()

            // 设置li高度
            liHeight = lrc.children[0].clientHeight;
            return result
        } else {
            console.log('歌词内容为空，首次加载');// 似乎已解决
            setTimeout(() => {
                getLrc(title.innerText)
            }, 50);
        }
    }
}

/**
 * 将一个时间字符串解析为数字
 * @param {*} timeStr 时间段字符串
 * @returns num
 */
function parseTime(timeStr) {
    var parts = timeStr.split(':');
    return +parts[0] * 60 + +parts[1]
}

/**
 * 计算出，在当前播放器播放到第几秒的情况下
 * lrcData数组中，应改高亮显示的歌词下标
 * 在0秒时不显示任何数据，也就是返回-1,
 */
function findIndex() {
    // 播放器当前时间
    var curTime = audio.currentTime;
    for (var i = 0; i < lrcData.length; i++) {
        if (curTime < lrcData[i].time) {
            return i - 1
        }
    }
    // 找遍了都没找到（说明播放到最后一句），就返回最后一句，不然会是undefined
    return lrcData.length - 1
}

/** 
 * 鼠标划入进度条事件
 * 显示一下时间
 * 后面改一下格式
 */
jdt.onmouseenter = function () {
    // 秒转换分钟00:00:00格式
    let outtime = audio.duration;
    let ingtime = audio.currentTime;
    function timeToMinute(times) {
        var t;
        if (times > -1) {
            var hour = Math.floor(times / 3600);
            var min = Math.floor(times / 60) % 60;
            var sec = times % 60;
            if (hour < 10) {
                t = '0' + hour + ":";
            } else {
                t = hour + ":";
            }

            if (min < 10) { t += "0"; }
            t += min + ":";
            if (sec < 10) { t += "0"; }
            t += sec.toFixed(2);
        }
        t = t.substring(0, t.length - 3);
        return t;
    }
    jdt.title = `总时长：${timeToMinute(outtime)}秒\n 当 前 ：${timeToMinute(ingtime)}秒`
}

/**
 * 创建歌词元素
 */
function createLrcElements() {
    lrc.innerHTML = ''
    /* 优化后，只改一次 dom 树，当然现在这里内容很少，可以不需要做这样的优化 */
    var frag = document.createDocumentFragment(); //文档片段
    for (var i = 0; i < lrcData.length; i++) {
        var li = document.createElement('li');
        li.textContent = lrcData[i].words;
        frag.appendChild(li);
    }
    lrc.appendChild(frag)
}

/**
 * 设置偏移量
 */
let Yindex;
let musicLrcHandmouse = false;
document.querySelector('#musicLrcHand').onmouseover = function () {// 鼠标移入后包括滚动时执行
    musicLrcHandmouse = true;
}
document.querySelector('#musicLrcHand').onmouseleave = function () {// 鼠标移出时执行
    musicLrcHandmouse = false;
}
function setOffset() {
    if (lrcNone == false) {
        var index = findIndex();
        if (Yindex == index || musicLrcHandmouse) {
            // 鼠标移入元素，不执行代码
        } else {
            Yindex = index
            var offset = liHeight * index + liHeight - containerHeight / 2;
            if (offset < 0) {
                offset = 0
            }
            // lrc.style.transform = `translateY(-${offset}px)`
            document.querySelector('#musicLrcHand').scroll(0, offset);
        }
        // 去掉之前的样式，因为歌词进度样式要一直设置，所以放if外面
        var li = lrc.querySelector('.active');
        if (li) {
            li.classList.remove('active');
            li.classList.add('visited');
        }
        li = lrc.children[index];
        if (li) {
            li.classList.add('active');
            li.style.height = liHeight;
        }
    }
}

audio.addEventListener('timeupdate', function () {
    setOffset()
})

// 进度条更新
function updateProgress(e) {
    // audio.duration: 音频长度
    // audio.currentTime: 音频播放位置
    // 对象解构操作
    const {
        duration,
        currentTime
    } = e.target;
    // e.target = {
    //     duration: 225,  // 当前音频时间长度 
    //     currentTime:0  // 当前播放时间
    // }
    const progressPercent = (currentTime / duration) * 100
    // 进度条
    progress.style.width = `${progressPercent}%`
}
// 设置进度条
function setProgress(e) {
    // progressContainer代理视图宽度
    const width = this.clientWidth
    // 鼠标点击时处于progressContainer里的水平偏移量
    const clickX = e.offsetX

    // audio.duration: 音频长度
    const duration = audio.duration

    // audio.currentTime: 音频播放位置
    audio.currentTime = (clickX / width) * duration
}
// 事件监听
// 1.播放歌曲
playBtn.onclick = function () {
    musicContainer.classList.contains('play') ? pauseSong() : playSong()
}
// 2.切换歌曲
prevBtn.onclick = prevSong
nextBtn.onclick = nextSong

// 3.播放器进度条相关
// 3.1 设置播放进度
progressContainer.onclick = setProgress
// 3.2 进度条更新
audio.ontimeupdate = updateProgress
// 3.3 歌曲结束后自动下一首
audio.onended = function () {
    nextSong();
    lrc.style.transform = `translateY(10px)`;
}

// 监听a标签点击后如果播放音乐就在新标签页打开
let links = document.querySelectorAll("a");
for (let i = 0; i < links.length; i++) {
    links[i].addEventListener("click", function () {
        if (!audio.paused) {
            // 音乐播放就加新标签也打开
            links[i].target = "_blank";
            // console.log(links[i]);
        }
    });
}